/*
 * Solifyn API
 * Welcome to the Solifyn API Reference. Leverage our secure endpoints to manage products and issue, validate, and manage software license keys programmatically.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.solifyn.api;

import com.solifyn.ApiCallback;
import com.solifyn.ApiClient;
import com.solifyn.ApiException;
import com.solifyn.ApiResponse;
import com.solifyn.Configuration;
import com.solifyn.Pair;
import com.solifyn.ProgressRequestBody;
import com.solifyn.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import com.solifyn.model.CheckoutLinkMessageResponseDto;
import com.solifyn.model.CheckoutLinkResponseDto;
import com.solifyn.model.CreateCheckoutLinkDto;
import com.solifyn.model.UpdateCheckoutLinkDto;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class CheckoutLinksApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public CheckoutLinksApi() {
        this(Configuration.getDefaultApiClient());
    }

    public CheckoutLinksApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for checkoutLinksCreate
     * @param createCheckoutLinkDto  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td> Checkout link created successfully. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call checkoutLinksCreateCall(CreateCheckoutLinkDto createCheckoutLinkDto, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = createCheckoutLinkDto;

        // create path and map variables
        String localVarPath = "/v1/checkout-links";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "ApiKeyAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call checkoutLinksCreateValidateBeforeCall(CreateCheckoutLinkDto createCheckoutLinkDto, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'createCheckoutLinkDto' is set
        if (createCheckoutLinkDto == null) {
            throw new ApiException("Missing the required parameter 'createCheckoutLinkDto' when calling checkoutLinksCreate(Async)");
        }

        return checkoutLinksCreateCall(createCheckoutLinkDto, _callback);

    }

    /**
     * Create Checkout Link
     * Generate a new checkout session link.
     * @param createCheckoutLinkDto  (required)
     * @return CheckoutLinkResponseDto
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td> Checkout link created successfully. </td><td>  -  </td></tr>
     </table>
     */
    public CheckoutLinkResponseDto checkoutLinksCreate(CreateCheckoutLinkDto createCheckoutLinkDto) throws ApiException {
        ApiResponse<CheckoutLinkResponseDto> localVarResp = checkoutLinksCreateWithHttpInfo(createCheckoutLinkDto);
        return localVarResp.getData();
    }

    /**
     * Create Checkout Link
     * Generate a new checkout session link.
     * @param createCheckoutLinkDto  (required)
     * @return ApiResponse&lt;CheckoutLinkResponseDto&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td> Checkout link created successfully. </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<CheckoutLinkResponseDto> checkoutLinksCreateWithHttpInfo(CreateCheckoutLinkDto createCheckoutLinkDto) throws ApiException {
        okhttp3.Call localVarCall = checkoutLinksCreateValidateBeforeCall(createCheckoutLinkDto, null);
        Type localVarReturnType = new TypeToken<CheckoutLinkResponseDto>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Create Checkout Link (asynchronously)
     * Generate a new checkout session link.
     * @param createCheckoutLinkDto  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td> Checkout link created successfully. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call checkoutLinksCreateAsync(CreateCheckoutLinkDto createCheckoutLinkDto, final ApiCallback<CheckoutLinkResponseDto> _callback) throws ApiException {

        okhttp3.Call localVarCall = checkoutLinksCreateValidateBeforeCall(createCheckoutLinkDto, _callback);
        Type localVarReturnType = new TypeToken<CheckoutLinkResponseDto>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for checkoutLinksDelete
     * @param id Checkout Link ID (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Checkout link deleted successfully. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call checkoutLinksDeleteCall(String id, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/v1/checkout-links/{id}"
            .replace("{" + "id" + "}", localVarApiClient.escapeString(id.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "ApiKeyAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "DELETE", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call checkoutLinksDeleteValidateBeforeCall(String id, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'id' is set
        if (id == null) {
            throw new ApiException("Missing the required parameter 'id' when calling checkoutLinksDelete(Async)");
        }

        return checkoutLinksDeleteCall(id, _callback);

    }

    /**
     * Delete Checkout Link
     * Permanently remove a checkout link.
     * @param id Checkout Link ID (required)
     * @return CheckoutLinkMessageResponseDto
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Checkout link deleted successfully. </td><td>  -  </td></tr>
     </table>
     */
    public CheckoutLinkMessageResponseDto checkoutLinksDelete(String id) throws ApiException {
        ApiResponse<CheckoutLinkMessageResponseDto> localVarResp = checkoutLinksDeleteWithHttpInfo(id);
        return localVarResp.getData();
    }

    /**
     * Delete Checkout Link
     * Permanently remove a checkout link.
     * @param id Checkout Link ID (required)
     * @return ApiResponse&lt;CheckoutLinkMessageResponseDto&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Checkout link deleted successfully. </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<CheckoutLinkMessageResponseDto> checkoutLinksDeleteWithHttpInfo(String id) throws ApiException {
        okhttp3.Call localVarCall = checkoutLinksDeleteValidateBeforeCall(id, null);
        Type localVarReturnType = new TypeToken<CheckoutLinkMessageResponseDto>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Delete Checkout Link (asynchronously)
     * Permanently remove a checkout link.
     * @param id Checkout Link ID (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Checkout link deleted successfully. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call checkoutLinksDeleteAsync(String id, final ApiCallback<CheckoutLinkMessageResponseDto> _callback) throws ApiException {

        okhttp3.Call localVarCall = checkoutLinksDeleteValidateBeforeCall(id, _callback);
        Type localVarReturnType = new TypeToken<CheckoutLinkMessageResponseDto>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for checkoutLinksGet
     * @param id Checkout Link ID (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Checkout link resolved successfully. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call checkoutLinksGetCall(String id, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/v1/checkout-links/{id}"
            .replace("{" + "id" + "}", localVarApiClient.escapeString(id.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "ApiKeyAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call checkoutLinksGetValidateBeforeCall(String id, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'id' is set
        if (id == null) {
            throw new ApiException("Missing the required parameter 'id' when calling checkoutLinksGet(Async)");
        }

        return checkoutLinksGetCall(id, _callback);

    }

    /**
     * Retrieve Checkout Link Details
     * Get details of a specific checkout link by ID (public access).
     * @param id Checkout Link ID (required)
     * @return CheckoutLinkResponseDto
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Checkout link resolved successfully. </td><td>  -  </td></tr>
     </table>
     */
    public CheckoutLinkResponseDto checkoutLinksGet(String id) throws ApiException {
        ApiResponse<CheckoutLinkResponseDto> localVarResp = checkoutLinksGetWithHttpInfo(id);
        return localVarResp.getData();
    }

    /**
     * Retrieve Checkout Link Details
     * Get details of a specific checkout link by ID (public access).
     * @param id Checkout Link ID (required)
     * @return ApiResponse&lt;CheckoutLinkResponseDto&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Checkout link resolved successfully. </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<CheckoutLinkResponseDto> checkoutLinksGetWithHttpInfo(String id) throws ApiException {
        okhttp3.Call localVarCall = checkoutLinksGetValidateBeforeCall(id, null);
        Type localVarReturnType = new TypeToken<CheckoutLinkResponseDto>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Retrieve Checkout Link Details (asynchronously)
     * Get details of a specific checkout link by ID (public access).
     * @param id Checkout Link ID (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Checkout link resolved successfully. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call checkoutLinksGetAsync(String id, final ApiCallback<CheckoutLinkResponseDto> _callback) throws ApiException {

        okhttp3.Call localVarCall = checkoutLinksGetValidateBeforeCall(id, _callback);
        Type localVarReturnType = new TypeToken<CheckoutLinkResponseDto>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for checkoutLinksList
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Checkout links retrieved successfully. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call checkoutLinksListCall(final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/v1/checkout-links";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "ApiKeyAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call checkoutLinksListValidateBeforeCall(final ApiCallback _callback) throws ApiException {
        return checkoutLinksListCall(_callback);

    }

    /**
     * List Checkout Links
     * Retrieve all active checkout session links for the active business.
     * @return List&lt;CheckoutLinkResponseDto&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Checkout links retrieved successfully. </td><td>  -  </td></tr>
     </table>
     */
    public List<CheckoutLinkResponseDto> checkoutLinksList() throws ApiException {
        ApiResponse<List<CheckoutLinkResponseDto>> localVarResp = checkoutLinksListWithHttpInfo();
        return localVarResp.getData();
    }

    /**
     * List Checkout Links
     * Retrieve all active checkout session links for the active business.
     * @return ApiResponse&lt;List&lt;CheckoutLinkResponseDto&gt;&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Checkout links retrieved successfully. </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<List<CheckoutLinkResponseDto>> checkoutLinksListWithHttpInfo() throws ApiException {
        okhttp3.Call localVarCall = checkoutLinksListValidateBeforeCall(null);
        Type localVarReturnType = new TypeToken<List<CheckoutLinkResponseDto>>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * List Checkout Links (asynchronously)
     * Retrieve all active checkout session links for the active business.
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Checkout links retrieved successfully. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call checkoutLinksListAsync(final ApiCallback<List<CheckoutLinkResponseDto>> _callback) throws ApiException {

        okhttp3.Call localVarCall = checkoutLinksListValidateBeforeCall(_callback);
        Type localVarReturnType = new TypeToken<List<CheckoutLinkResponseDto>>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for checkoutLinksUpdate
     * @param id Checkout Link ID (required)
     * @param updateCheckoutLinkDto  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Checkout link updated successfully. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call checkoutLinksUpdateCall(String id, UpdateCheckoutLinkDto updateCheckoutLinkDto, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = updateCheckoutLinkDto;

        // create path and map variables
        String localVarPath = "/v1/checkout-links/{id}"
            .replace("{" + "id" + "}", localVarApiClient.escapeString(id.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "ApiKeyAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "PATCH", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call checkoutLinksUpdateValidateBeforeCall(String id, UpdateCheckoutLinkDto updateCheckoutLinkDto, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'id' is set
        if (id == null) {
            throw new ApiException("Missing the required parameter 'id' when calling checkoutLinksUpdate(Async)");
        }

        // verify the required parameter 'updateCheckoutLinkDto' is set
        if (updateCheckoutLinkDto == null) {
            throw new ApiException("Missing the required parameter 'updateCheckoutLinkDto' when calling checkoutLinksUpdate(Async)");
        }

        return checkoutLinksUpdateCall(id, updateCheckoutLinkDto, _callback);

    }

    /**
     * Update Checkout Link
     * Update title, custom pricing, redirection URLs, or friendly inputs for a checkout link.
     * @param id Checkout Link ID (required)
     * @param updateCheckoutLinkDto  (required)
     * @return CheckoutLinkMessageResponseDto
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Checkout link updated successfully. </td><td>  -  </td></tr>
     </table>
     */
    public CheckoutLinkMessageResponseDto checkoutLinksUpdate(String id, UpdateCheckoutLinkDto updateCheckoutLinkDto) throws ApiException {
        ApiResponse<CheckoutLinkMessageResponseDto> localVarResp = checkoutLinksUpdateWithHttpInfo(id, updateCheckoutLinkDto);
        return localVarResp.getData();
    }

    /**
     * Update Checkout Link
     * Update title, custom pricing, redirection URLs, or friendly inputs for a checkout link.
     * @param id Checkout Link ID (required)
     * @param updateCheckoutLinkDto  (required)
     * @return ApiResponse&lt;CheckoutLinkMessageResponseDto&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Checkout link updated successfully. </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<CheckoutLinkMessageResponseDto> checkoutLinksUpdateWithHttpInfo(String id, UpdateCheckoutLinkDto updateCheckoutLinkDto) throws ApiException {
        okhttp3.Call localVarCall = checkoutLinksUpdateValidateBeforeCall(id, updateCheckoutLinkDto, null);
        Type localVarReturnType = new TypeToken<CheckoutLinkMessageResponseDto>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Update Checkout Link (asynchronously)
     * Update title, custom pricing, redirection URLs, or friendly inputs for a checkout link.
     * @param id Checkout Link ID (required)
     * @param updateCheckoutLinkDto  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Checkout link updated successfully. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call checkoutLinksUpdateAsync(String id, UpdateCheckoutLinkDto updateCheckoutLinkDto, final ApiCallback<CheckoutLinkMessageResponseDto> _callback) throws ApiException {

        okhttp3.Call localVarCall = checkoutLinksUpdateValidateBeforeCall(id, updateCheckoutLinkDto, _callback);
        Type localVarReturnType = new TypeToken<CheckoutLinkMessageResponseDto>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
}
