/*
 * Solifyn API
 * Welcome to the Solifyn API Reference. Leverage our secure endpoints to manage products and issue, validate, and manage software license keys programmatically.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.solifyn.api;

import com.solifyn.ApiCallback;
import com.solifyn.ApiClient;
import com.solifyn.ApiException;
import com.solifyn.ApiResponse;
import com.solifyn.Configuration;
import com.solifyn.Pair;
import com.solifyn.ProgressRequestBody;
import com.solifyn.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import com.solifyn.model.Instance;
import com.solifyn.model.License;
import com.solifyn.model.LicensesCreateRequest;
import com.solifyn.model.LicensesUpdateInstancePostRequest;
import com.solifyn.model.LicensesUpdateRequest;
import java.util.UUID;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class LicenseApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public LicenseApi() {
        this(Configuration.getDefaultApiClient());
    }

    public LicenseApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for licensesCreate
     * @param licensesCreateRequest  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successfully created license. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call licensesCreateCall(LicensesCreateRequest licensesCreateRequest, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = licensesCreateRequest;

        // create path and map variables
        String localVarPath = "/v1/licenses";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "ApiKeyAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call licensesCreateValidateBeforeCall(LicensesCreateRequest licensesCreateRequest, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'licensesCreateRequest' is set
        if (licensesCreateRequest == null) {
            throw new ApiException("Missing the required parameter 'licensesCreateRequest' when calling licensesCreate(Async)");
        }

        return licensesCreateCall(licensesCreateRequest, _callback);

    }

    /**
     * Create License Key
     * Manually issue a new license key for a specific product.
     * @param licensesCreateRequest  (required)
     * @return License
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successfully created license. </td><td>  -  </td></tr>
     </table>
     */
    public License licensesCreate(LicensesCreateRequest licensesCreateRequest) throws ApiException {
        ApiResponse<License> localVarResp = licensesCreateWithHttpInfo(licensesCreateRequest);
        return localVarResp.getData();
    }

    /**
     * Create License Key
     * Manually issue a new license key for a specific product.
     * @param licensesCreateRequest  (required)
     * @return ApiResponse&lt;License&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successfully created license. </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<License> licensesCreateWithHttpInfo(LicensesCreateRequest licensesCreateRequest) throws ApiException {
        okhttp3.Call localVarCall = licensesCreateValidateBeforeCall(licensesCreateRequest, null);
        Type localVarReturnType = new TypeToken<License>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Create License Key (asynchronously)
     * Manually issue a new license key for a specific product.
     * @param licensesCreateRequest  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successfully created license. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call licensesCreateAsync(LicensesCreateRequest licensesCreateRequest, final ApiCallback<License> _callback) throws ApiException {

        okhttp3.Call localVarCall = licensesCreateValidateBeforeCall(licensesCreateRequest, _callback);
        Type localVarReturnType = new TypeToken<License>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for licensesDeleteInstance
     * @param instanceId The unique hardware activation instance ID. (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Instance deactivated/deleted successfully. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call licensesDeleteInstanceCall(String instanceId, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/v1/licenses/instances/{instanceId}"
            .replace("{" + "instanceId" + "}", localVarApiClient.escapeString(instanceId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "ApiKeyAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "DELETE", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call licensesDeleteInstanceValidateBeforeCall(String instanceId, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'instanceId' is set
        if (instanceId == null) {
            throw new ApiException("Missing the required parameter 'instanceId' when calling licensesDeleteInstance(Async)");
        }

        return licensesDeleteInstanceCall(instanceId, _callback);

    }

    /**
     * Force Delete Instance
     * Administrative endpoint to force-delete an instance globally by its database ID.
     * @param instanceId The unique hardware activation instance ID. (required)
     * @return Instance
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Instance deactivated/deleted successfully. </td><td>  -  </td></tr>
     </table>
     */
    public Instance licensesDeleteInstance(String instanceId) throws ApiException {
        ApiResponse<Instance> localVarResp = licensesDeleteInstanceWithHttpInfo(instanceId);
        return localVarResp.getData();
    }

    /**
     * Force Delete Instance
     * Administrative endpoint to force-delete an instance globally by its database ID.
     * @param instanceId The unique hardware activation instance ID. (required)
     * @return ApiResponse&lt;Instance&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Instance deactivated/deleted successfully. </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Instance> licensesDeleteInstanceWithHttpInfo(String instanceId) throws ApiException {
        okhttp3.Call localVarCall = licensesDeleteInstanceValidateBeforeCall(instanceId, null);
        Type localVarReturnType = new TypeToken<Instance>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Force Delete Instance (asynchronously)
     * Administrative endpoint to force-delete an instance globally by its database ID.
     * @param instanceId The unique hardware activation instance ID. (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Instance deactivated/deleted successfully. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call licensesDeleteInstanceAsync(String instanceId, final ApiCallback<Instance> _callback) throws ApiException {

        okhttp3.Call localVarCall = licensesDeleteInstanceValidateBeforeCall(instanceId, _callback);
        Type localVarReturnType = new TypeToken<Instance>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for licensesGet
     * @param id The unique license key ID. (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successfully retrieved license details. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call licensesGetCall(UUID id, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/v1/licenses/{id}"
            .replace("{" + "id" + "}", localVarApiClient.escapeString(id.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "ApiKeyAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call licensesGetValidateBeforeCall(UUID id, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'id' is set
        if (id == null) {
            throw new ApiException("Missing the required parameter 'id' when calling licensesGet(Async)");
        }

        return licensesGetCall(id, _callback);

    }

    /**
     * Get License Key
     * Retrieve complete administrative details of a specific license key.
     * @param id The unique license key ID. (required)
     * @return License
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successfully retrieved license details. </td><td>  -  </td></tr>
     </table>
     */
    public License licensesGet(UUID id) throws ApiException {
        ApiResponse<License> localVarResp = licensesGetWithHttpInfo(id);
        return localVarResp.getData();
    }

    /**
     * Get License Key
     * Retrieve complete administrative details of a specific license key.
     * @param id The unique license key ID. (required)
     * @return ApiResponse&lt;License&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successfully retrieved license details. </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<License> licensesGetWithHttpInfo(UUID id) throws ApiException {
        okhttp3.Call localVarCall = licensesGetValidateBeforeCall(id, null);
        Type localVarReturnType = new TypeToken<License>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Get License Key (asynchronously)
     * Retrieve complete administrative details of a specific license key.
     * @param id The unique license key ID. (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successfully retrieved license details. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call licensesGetAsync(UUID id, final ApiCallback<License> _callback) throws ApiException {

        okhttp3.Call localVarCall = licensesGetValidateBeforeCall(id, _callback);
        Type localVarReturnType = new TypeToken<License>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for licensesGetInstance
     * @param id The unique administrative identifier (ID) of the parent license key. (required)
     * @param instanceId The client-generated instance ID (hardware hash) or the internal database ID of the instance. (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successfully retrieved instance. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call licensesGetInstanceCall(UUID id, String instanceId, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/v1/licenses/{id}/instances/{instanceId}"
            .replace("{" + "id" + "}", localVarApiClient.escapeString(id.toString()))
            .replace("{" + "instanceId" + "}", localVarApiClient.escapeString(instanceId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "ApiKeyAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call licensesGetInstanceValidateBeforeCall(UUID id, String instanceId, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'id' is set
        if (id == null) {
            throw new ApiException("Missing the required parameter 'id' when calling licensesGetInstance(Async)");
        }

        // verify the required parameter 'instanceId' is set
        if (instanceId == null) {
            throw new ApiException("Missing the required parameter 'instanceId' when calling licensesGetInstance(Async)");
        }

        return licensesGetInstanceCall(id, instanceId, _callback);

    }

    /**
     * Get License Key Instance
     * Retrieve administrative details of a specific software license instance.
     * @param id The unique administrative identifier (ID) of the parent license key. (required)
     * @param instanceId The client-generated instance ID (hardware hash) or the internal database ID of the instance. (required)
     * @return Instance
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successfully retrieved instance. </td><td>  -  </td></tr>
     </table>
     */
    public Instance licensesGetInstance(UUID id, String instanceId) throws ApiException {
        ApiResponse<Instance> localVarResp = licensesGetInstanceWithHttpInfo(id, instanceId);
        return localVarResp.getData();
    }

    /**
     * Get License Key Instance
     * Retrieve administrative details of a specific software license instance.
     * @param id The unique administrative identifier (ID) of the parent license key. (required)
     * @param instanceId The client-generated instance ID (hardware hash) or the internal database ID of the instance. (required)
     * @return ApiResponse&lt;Instance&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successfully retrieved instance. </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Instance> licensesGetInstanceWithHttpInfo(UUID id, String instanceId) throws ApiException {
        okhttp3.Call localVarCall = licensesGetInstanceValidateBeforeCall(id, instanceId, null);
        Type localVarReturnType = new TypeToken<Instance>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Get License Key Instance (asynchronously)
     * Retrieve administrative details of a specific software license instance.
     * @param id The unique administrative identifier (ID) of the parent license key. (required)
     * @param instanceId The client-generated instance ID (hardware hash) or the internal database ID of the instance. (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successfully retrieved instance. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call licensesGetInstanceAsync(UUID id, String instanceId, final ApiCallback<Instance> _callback) throws ApiException {

        okhttp3.Call localVarCall = licensesGetInstanceValidateBeforeCall(id, instanceId, _callback);
        Type localVarReturnType = new TypeToken<Instance>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for licensesGetInstances
     * @param id The unique administrative identifier (ID) of the parent license key. (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successfully retrieved instances. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call licensesGetInstancesCall(String id, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/v1/licenses/{id}/instances"
            .replace("{" + "id" + "}", localVarApiClient.escapeString(id.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "ApiKeyAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call licensesGetInstancesValidateBeforeCall(String id, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'id' is set
        if (id == null) {
            throw new ApiException("Missing the required parameter 'id' when calling licensesGetInstances(Async)");
        }

        return licensesGetInstancesCall(id, _callback);

    }

    /**
     * Get License Key Instances
     * Retrieve all active devices/instances for a specific administrative license key.
     * @param id The unique administrative identifier (ID) of the parent license key. (required)
     * @return List&lt;Instance&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successfully retrieved instances. </td><td>  -  </td></tr>
     </table>
     */
    public List<Instance> licensesGetInstances(String id) throws ApiException {
        ApiResponse<List<Instance>> localVarResp = licensesGetInstancesWithHttpInfo(id);
        return localVarResp.getData();
    }

    /**
     * Get License Key Instances
     * Retrieve all active devices/instances for a specific administrative license key.
     * @param id The unique administrative identifier (ID) of the parent license key. (required)
     * @return ApiResponse&lt;List&lt;Instance&gt;&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successfully retrieved instances. </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<List<Instance>> licensesGetInstancesWithHttpInfo(String id) throws ApiException {
        okhttp3.Call localVarCall = licensesGetInstancesValidateBeforeCall(id, null);
        Type localVarReturnType = new TypeToken<List<Instance>>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Get License Key Instances (asynchronously)
     * Retrieve all active devices/instances for a specific administrative license key.
     * @param id The unique administrative identifier (ID) of the parent license key. (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successfully retrieved instances. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call licensesGetInstancesAsync(String id, final ApiCallback<List<Instance>> _callback) throws ApiException {

        okhttp3.Call localVarCall = licensesGetInstancesValidateBeforeCall(id, _callback);
        Type localVarReturnType = new TypeToken<List<Instance>>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for licensesList
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successfully retrieved licenses list. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call licensesListCall(final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/v1/licenses";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "ApiKeyAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call licensesListValidateBeforeCall(final ApiCallback _callback) throws ApiException {
        return licensesListCall(_callback);

    }

    /**
     * List License Keys
     * List all administrative license keys belonging to products under your active business.
     * @return List&lt;License&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successfully retrieved licenses list. </td><td>  -  </td></tr>
     </table>
     */
    public List<License> licensesList() throws ApiException {
        ApiResponse<List<License>> localVarResp = licensesListWithHttpInfo();
        return localVarResp.getData();
    }

    /**
     * List License Keys
     * List all administrative license keys belonging to products under your active business.
     * @return ApiResponse&lt;List&lt;License&gt;&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successfully retrieved licenses list. </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<List<License>> licensesListWithHttpInfo() throws ApiException {
        okhttp3.Call localVarCall = licensesListValidateBeforeCall(null);
        Type localVarReturnType = new TypeToken<List<License>>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * List License Keys (asynchronously)
     * List all administrative license keys belonging to products under your active business.
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successfully retrieved licenses list. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call licensesListAsync(final ApiCallback<List<License>> _callback) throws ApiException {

        okhttp3.Call localVarCall = licensesListValidateBeforeCall(_callback);
        Type localVarReturnType = new TypeToken<List<License>>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for licensesToggle
     * @param id The unique license key ID. (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Status toggled successfully. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call licensesToggleCall(String id, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/v1/licenses/{id}/toggle"
            .replace("{" + "id" + "}", localVarApiClient.escapeString(id.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "ApiKeyAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call licensesToggleValidateBeforeCall(String id, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'id' is set
        if (id == null) {
            throw new ApiException("Missing the required parameter 'id' when calling licensesToggle(Async)");
        }

        return licensesToggleCall(id, _callback);

    }

    /**
     * Toggle License Status
     * Toggle the status of a specific license key between ACTIVE and DISABLED.
     * @param id The unique license key ID. (required)
     * @return License
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Status toggled successfully. </td><td>  -  </td></tr>
     </table>
     */
    public License licensesToggle(String id) throws ApiException {
        ApiResponse<License> localVarResp = licensesToggleWithHttpInfo(id);
        return localVarResp.getData();
    }

    /**
     * Toggle License Status
     * Toggle the status of a specific license key between ACTIVE and DISABLED.
     * @param id The unique license key ID. (required)
     * @return ApiResponse&lt;License&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Status toggled successfully. </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<License> licensesToggleWithHttpInfo(String id) throws ApiException {
        okhttp3.Call localVarCall = licensesToggleValidateBeforeCall(id, null);
        Type localVarReturnType = new TypeToken<License>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Toggle License Status (asynchronously)
     * Toggle the status of a specific license key between ACTIVE and DISABLED.
     * @param id The unique license key ID. (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Status toggled successfully. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call licensesToggleAsync(String id, final ApiCallback<License> _callback) throws ApiException {

        okhttp3.Call localVarCall = licensesToggleValidateBeforeCall(id, _callback);
        Type localVarReturnType = new TypeToken<License>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for licensesUpdate
     * @param id The unique license key ID. (required)
     * @param licensesUpdateRequest  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successfully updated license. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call licensesUpdateCall(UUID id, LicensesUpdateRequest licensesUpdateRequest, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = licensesUpdateRequest;

        // create path and map variables
        String localVarPath = "/v1/licenses/{id}"
            .replace("{" + "id" + "}", localVarApiClient.escapeString(id.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "ApiKeyAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "PATCH", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call licensesUpdateValidateBeforeCall(UUID id, LicensesUpdateRequest licensesUpdateRequest, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'id' is set
        if (id == null) {
            throw new ApiException("Missing the required parameter 'id' when calling licensesUpdate(Async)");
        }

        // verify the required parameter 'licensesUpdateRequest' is set
        if (licensesUpdateRequest == null) {
            throw new ApiException("Missing the required parameter 'licensesUpdateRequest' when calling licensesUpdate(Async)");
        }

        return licensesUpdateCall(id, licensesUpdateRequest, _callback);

    }

    /**
     * Update License Key
     * Update limits or status of an existing license key.
     * @param id The unique license key ID. (required)
     * @param licensesUpdateRequest  (required)
     * @return License
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successfully updated license. </td><td>  -  </td></tr>
     </table>
     */
    public License licensesUpdate(UUID id, LicensesUpdateRequest licensesUpdateRequest) throws ApiException {
        ApiResponse<License> localVarResp = licensesUpdateWithHttpInfo(id, licensesUpdateRequest);
        return localVarResp.getData();
    }

    /**
     * Update License Key
     * Update limits or status of an existing license key.
     * @param id The unique license key ID. (required)
     * @param licensesUpdateRequest  (required)
     * @return ApiResponse&lt;License&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successfully updated license. </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<License> licensesUpdateWithHttpInfo(UUID id, LicensesUpdateRequest licensesUpdateRequest) throws ApiException {
        okhttp3.Call localVarCall = licensesUpdateValidateBeforeCall(id, licensesUpdateRequest, null);
        Type localVarReturnType = new TypeToken<License>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Update License Key (asynchronously)
     * Update limits or status of an existing license key.
     * @param id The unique license key ID. (required)
     * @param licensesUpdateRequest  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successfully updated license. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call licensesUpdateAsync(UUID id, LicensesUpdateRequest licensesUpdateRequest, final ApiCallback<License> _callback) throws ApiException {

        okhttp3.Call localVarCall = licensesUpdateValidateBeforeCall(id, licensesUpdateRequest, _callback);
        Type localVarReturnType = new TypeToken<License>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for licensesUpdateInstance
     * @param instanceId The client-generated instance ID (hardware hash) or the internal database ID of the instance. (required)
     * @param id The unique administrative identifier (ID) of the parent license key. (required)
     * @param licensesUpdateInstancePostRequest  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successfully updated instance. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call licensesUpdateInstanceCall(String instanceId, UUID id, LicensesUpdateInstancePostRequest licensesUpdateInstancePostRequest, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = licensesUpdateInstancePostRequest;

        // create path and map variables
        String localVarPath = "/v1/licenses/{id}/instances/{instanceId}"
            .replace("{" + "instanceId" + "}", localVarApiClient.escapeString(instanceId.toString()))
            .replace("{" + "id" + "}", localVarApiClient.escapeString(id.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "ApiKeyAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "PATCH", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call licensesUpdateInstanceValidateBeforeCall(String instanceId, UUID id, LicensesUpdateInstancePostRequest licensesUpdateInstancePostRequest, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'instanceId' is set
        if (instanceId == null) {
            throw new ApiException("Missing the required parameter 'instanceId' when calling licensesUpdateInstance(Async)");
        }

        // verify the required parameter 'id' is set
        if (id == null) {
            throw new ApiException("Missing the required parameter 'id' when calling licensesUpdateInstance(Async)");
        }

        // verify the required parameter 'licensesUpdateInstancePostRequest' is set
        if (licensesUpdateInstancePostRequest == null) {
            throw new ApiException("Missing the required parameter 'licensesUpdateInstancePostRequest' when calling licensesUpdateInstance(Async)");
        }

        return licensesUpdateInstanceCall(instanceId, id, licensesUpdateInstancePostRequest, _callback);

    }

    /**
     * Update License Key Instance
     * Update administrative details (like friendly display name or custom IP) of an active license device instance.
     * @param instanceId The client-generated instance ID (hardware hash) or the internal database ID of the instance. (required)
     * @param id The unique administrative identifier (ID) of the parent license key. (required)
     * @param licensesUpdateInstancePostRequest  (required)
     * @return Instance
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successfully updated instance. </td><td>  -  </td></tr>
     </table>
     */
    public Instance licensesUpdateInstance(String instanceId, UUID id, LicensesUpdateInstancePostRequest licensesUpdateInstancePostRequest) throws ApiException {
        ApiResponse<Instance> localVarResp = licensesUpdateInstanceWithHttpInfo(instanceId, id, licensesUpdateInstancePostRequest);
        return localVarResp.getData();
    }

    /**
     * Update License Key Instance
     * Update administrative details (like friendly display name or custom IP) of an active license device instance.
     * @param instanceId The client-generated instance ID (hardware hash) or the internal database ID of the instance. (required)
     * @param id The unique administrative identifier (ID) of the parent license key. (required)
     * @param licensesUpdateInstancePostRequest  (required)
     * @return ApiResponse&lt;Instance&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successfully updated instance. </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Instance> licensesUpdateInstanceWithHttpInfo(String instanceId, UUID id, LicensesUpdateInstancePostRequest licensesUpdateInstancePostRequest) throws ApiException {
        okhttp3.Call localVarCall = licensesUpdateInstanceValidateBeforeCall(instanceId, id, licensesUpdateInstancePostRequest, null);
        Type localVarReturnType = new TypeToken<Instance>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Update License Key Instance (asynchronously)
     * Update administrative details (like friendly display name or custom IP) of an active license device instance.
     * @param instanceId The client-generated instance ID (hardware hash) or the internal database ID of the instance. (required)
     * @param id The unique administrative identifier (ID) of the parent license key. (required)
     * @param licensesUpdateInstancePostRequest  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successfully updated instance. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call licensesUpdateInstanceAsync(String instanceId, UUID id, LicensesUpdateInstancePostRequest licensesUpdateInstancePostRequest, final ApiCallback<Instance> _callback) throws ApiException {

        okhttp3.Call localVarCall = licensesUpdateInstanceValidateBeforeCall(instanceId, id, licensesUpdateInstancePostRequest, _callback);
        Type localVarReturnType = new TypeToken<Instance>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for licensesUpdateInstancePost
     * @param instanceId The client-generated instance ID (hardware hash) or the internal database ID of the instance. (required)
     * @param id The unique administrative identifier (ID) of the parent license key. (required)
     * @param licensesUpdateInstancePostRequest  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successfully updated instance. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call licensesUpdateInstancePostCall(String instanceId, UUID id, LicensesUpdateInstancePostRequest licensesUpdateInstancePostRequest, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = licensesUpdateInstancePostRequest;

        // create path and map variables
        String localVarPath = "/v1/licenses/{id}/instances/{instanceId}"
            .replace("{" + "instanceId" + "}", localVarApiClient.escapeString(instanceId.toString()))
            .replace("{" + "id" + "}", localVarApiClient.escapeString(id.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "ApiKeyAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call licensesUpdateInstancePostValidateBeforeCall(String instanceId, UUID id, LicensesUpdateInstancePostRequest licensesUpdateInstancePostRequest, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'instanceId' is set
        if (instanceId == null) {
            throw new ApiException("Missing the required parameter 'instanceId' when calling licensesUpdateInstancePost(Async)");
        }

        // verify the required parameter 'id' is set
        if (id == null) {
            throw new ApiException("Missing the required parameter 'id' when calling licensesUpdateInstancePost(Async)");
        }

        // verify the required parameter 'licensesUpdateInstancePostRequest' is set
        if (licensesUpdateInstancePostRequest == null) {
            throw new ApiException("Missing the required parameter 'licensesUpdateInstancePostRequest' when calling licensesUpdateInstancePost(Async)");
        }

        return licensesUpdateInstancePostCall(instanceId, id, licensesUpdateInstancePostRequest, _callback);

    }

    /**
     * Update License Key Instance (POST)
     * Alternative POST endpoint to update administrative details (like friendly display name or custom IP) of an active license device instance.
     * @param instanceId The client-generated instance ID (hardware hash) or the internal database ID of the instance. (required)
     * @param id The unique administrative identifier (ID) of the parent license key. (required)
     * @param licensesUpdateInstancePostRequest  (required)
     * @return Instance
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successfully updated instance. </td><td>  -  </td></tr>
     </table>
     */
    public Instance licensesUpdateInstancePost(String instanceId, UUID id, LicensesUpdateInstancePostRequest licensesUpdateInstancePostRequest) throws ApiException {
        ApiResponse<Instance> localVarResp = licensesUpdateInstancePostWithHttpInfo(instanceId, id, licensesUpdateInstancePostRequest);
        return localVarResp.getData();
    }

    /**
     * Update License Key Instance (POST)
     * Alternative POST endpoint to update administrative details (like friendly display name or custom IP) of an active license device instance.
     * @param instanceId The client-generated instance ID (hardware hash) or the internal database ID of the instance. (required)
     * @param id The unique administrative identifier (ID) of the parent license key. (required)
     * @param licensesUpdateInstancePostRequest  (required)
     * @return ApiResponse&lt;Instance&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successfully updated instance. </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Instance> licensesUpdateInstancePostWithHttpInfo(String instanceId, UUID id, LicensesUpdateInstancePostRequest licensesUpdateInstancePostRequest) throws ApiException {
        okhttp3.Call localVarCall = licensesUpdateInstancePostValidateBeforeCall(instanceId, id, licensesUpdateInstancePostRequest, null);
        Type localVarReturnType = new TypeToken<Instance>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Update License Key Instance (POST) (asynchronously)
     * Alternative POST endpoint to update administrative details (like friendly display name or custom IP) of an active license device instance.
     * @param instanceId The client-generated instance ID (hardware hash) or the internal database ID of the instance. (required)
     * @param id The unique administrative identifier (ID) of the parent license key. (required)
     * @param licensesUpdateInstancePostRequest  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successfully updated instance. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call licensesUpdateInstancePostAsync(String instanceId, UUID id, LicensesUpdateInstancePostRequest licensesUpdateInstancePostRequest, final ApiCallback<Instance> _callback) throws ApiException {

        okhttp3.Call localVarCall = licensesUpdateInstancePostValidateBeforeCall(instanceId, id, licensesUpdateInstancePostRequest, _callback);
        Type localVarReturnType = new TypeToken<Instance>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
}
