/*
 * Solifyn API
 * Welcome to the Solifyn API Reference. Leverage our secure endpoints to manage products and issue, validate, and manage software license keys programmatically.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.solifyn.api;

import com.solifyn.ApiCallback;
import com.solifyn.ApiClient;
import com.solifyn.ApiException;
import com.solifyn.ApiResponse;
import com.solifyn.Configuration;
import com.solifyn.Pair;
import com.solifyn.ProgressRequestBody;
import com.solifyn.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import java.math.BigDecimal;
import com.solifyn.model.Invoice;
import com.solifyn.model.Order;
import com.solifyn.model.OrderList;
import com.solifyn.model.OrderRefundCreate;
import com.solifyn.model.OrderUpdate;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class OrdersApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public OrdersApi() {
        this(Configuration.getDefaultApiClient());
    }

    public OrdersApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for ordersGet
     * @param id The unique order/payment ID. (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Order resolved successfully. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call ordersGetCall(String id, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/v1/orders/{id}"
            .replace("{" + "id" + "}", localVarApiClient.escapeString(id.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "ApiKeyAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call ordersGetValidateBeforeCall(String id, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'id' is set
        if (id == null) {
            throw new ApiException("Missing the required parameter 'id' when calling ordersGet(Async)");
        }

        return ordersGetCall(id, _callback);

    }

    /**
     * Retrieve Order
     * Retrieve details of a specific order/payment by ID.
     * @param id The unique order/payment ID. (required)
     * @return Order
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Order resolved successfully. </td><td>  -  </td></tr>
     </table>
     */
    public Order ordersGet(String id) throws ApiException {
        ApiResponse<Order> localVarResp = ordersGetWithHttpInfo(id);
        return localVarResp.getData();
    }

    /**
     * Retrieve Order
     * Retrieve details of a specific order/payment by ID.
     * @param id The unique order/payment ID. (required)
     * @return ApiResponse&lt;Order&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Order resolved successfully. </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Order> ordersGetWithHttpInfo(String id) throws ApiException {
        okhttp3.Call localVarCall = ordersGetValidateBeforeCall(id, null);
        Type localVarReturnType = new TypeToken<Order>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Retrieve Order (asynchronously)
     * Retrieve details of a specific order/payment by ID.
     * @param id The unique order/payment ID. (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Order resolved successfully. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call ordersGetAsync(String id, final ApiCallback<Order> _callback) throws ApiException {

        okhttp3.Call localVarCall = ordersGetValidateBeforeCall(id, _callback);
        Type localVarReturnType = new TypeToken<Order>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for ordersGetInvoice
     * @param id The unique order/payment ID. (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Invoice retrieved successfully. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call ordersGetInvoiceCall(String id, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/v1/orders/{id}/invoice"
            .replace("{" + "id" + "}", localVarApiClient.escapeString(id.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call ordersGetInvoiceValidateBeforeCall(String id, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'id' is set
        if (id == null) {
            throw new ApiException("Missing the required parameter 'id' when calling ordersGetInvoice(Async)");
        }

        return ordersGetInvoiceCall(id, _callback);

    }

    /**
     * Get Order Invoice
     * Retrieve the generated invoice details for the specified order.
     * @param id The unique order/payment ID. (required)
     * @return Invoice
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Invoice retrieved successfully. </td><td>  -  </td></tr>
     </table>
     */
    public Invoice ordersGetInvoice(String id) throws ApiException {
        ApiResponse<Invoice> localVarResp = ordersGetInvoiceWithHttpInfo(id);
        return localVarResp.getData();
    }

    /**
     * Get Order Invoice
     * Retrieve the generated invoice details for the specified order.
     * @param id The unique order/payment ID. (required)
     * @return ApiResponse&lt;Invoice&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Invoice retrieved successfully. </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Invoice> ordersGetInvoiceWithHttpInfo(String id) throws ApiException {
        okhttp3.Call localVarCall = ordersGetInvoiceValidateBeforeCall(id, null);
        Type localVarReturnType = new TypeToken<Invoice>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Get Order Invoice (asynchronously)
     * Retrieve the generated invoice details for the specified order.
     * @param id The unique order/payment ID. (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Invoice retrieved successfully. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call ordersGetInvoiceAsync(String id, final ApiCallback<Invoice> _callback) throws ApiException {

        okhttp3.Call localVarCall = ordersGetInvoiceValidateBeforeCall(id, _callback);
        Type localVarReturnType = new TypeToken<Invoice>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for ordersList
     * @param createdAtLte Filter by creation date less than or equal to. (optional)
     * @param createdAtGte Filter by creation date greater than or equal to. (optional)
     * @param productId Filter by product identifier. (optional)
     * @param customerId Filter by customer identifier. (optional)
     * @param status Filter by order/payment status. (optional)
     * @param pageSize Size of a page, defaults to 10. Maximum is 100. (optional, default to 10)
     * @param pageNumber Page number, defaults to 1. (optional, default to 1)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> List of orders/payments retrieved successfully. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call ordersListCall(String createdAtLte, String createdAtGte, String productId, String customerId, String status, BigDecimal pageSize, BigDecimal pageNumber, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/v1/orders";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (createdAtLte != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("createdAtLte", createdAtLte));
        }

        if (createdAtGte != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("createdAtGte", createdAtGte));
        }

        if (productId != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("product_id", productId));
        }

        if (customerId != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("customer_id", customerId));
        }

        if (status != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("status", status));
        }

        if (pageSize != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("pageSize", pageSize));
        }

        if (pageNumber != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("pageNumber", pageNumber));
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "ApiKeyAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call ordersListValidateBeforeCall(String createdAtLte, String createdAtGte, String productId, String customerId, String status, BigDecimal pageSize, BigDecimal pageNumber, final ApiCallback _callback) throws ApiException {
        return ordersListCall(createdAtLte, createdAtGte, productId, customerId, status, pageSize, pageNumber, _callback);

    }

    /**
     * List Orders
     * List and query orders/payments belonging to your active business.
     * @param createdAtLte Filter by creation date less than or equal to. (optional)
     * @param createdAtGte Filter by creation date greater than or equal to. (optional)
     * @param productId Filter by product identifier. (optional)
     * @param customerId Filter by customer identifier. (optional)
     * @param status Filter by order/payment status. (optional)
     * @param pageSize Size of a page, defaults to 10. Maximum is 100. (optional, default to 10)
     * @param pageNumber Page number, defaults to 1. (optional, default to 1)
     * @return OrderList
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> List of orders/payments retrieved successfully. </td><td>  -  </td></tr>
     </table>
     */
    public OrderList ordersList(String createdAtLte, String createdAtGte, String productId, String customerId, String status, BigDecimal pageSize, BigDecimal pageNumber) throws ApiException {
        ApiResponse<OrderList> localVarResp = ordersListWithHttpInfo(createdAtLte, createdAtGte, productId, customerId, status, pageSize, pageNumber);
        return localVarResp.getData();
    }

    /**
     * List Orders
     * List and query orders/payments belonging to your active business.
     * @param createdAtLte Filter by creation date less than or equal to. (optional)
     * @param createdAtGte Filter by creation date greater than or equal to. (optional)
     * @param productId Filter by product identifier. (optional)
     * @param customerId Filter by customer identifier. (optional)
     * @param status Filter by order/payment status. (optional)
     * @param pageSize Size of a page, defaults to 10. Maximum is 100. (optional, default to 10)
     * @param pageNumber Page number, defaults to 1. (optional, default to 1)
     * @return ApiResponse&lt;OrderList&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> List of orders/payments retrieved successfully. </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<OrderList> ordersListWithHttpInfo(String createdAtLte, String createdAtGte, String productId, String customerId, String status, BigDecimal pageSize, BigDecimal pageNumber) throws ApiException {
        okhttp3.Call localVarCall = ordersListValidateBeforeCall(createdAtLte, createdAtGte, productId, customerId, status, pageSize, pageNumber, null);
        Type localVarReturnType = new TypeToken<OrderList>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * List Orders (asynchronously)
     * List and query orders/payments belonging to your active business.
     * @param createdAtLte Filter by creation date less than or equal to. (optional)
     * @param createdAtGte Filter by creation date greater than or equal to. (optional)
     * @param productId Filter by product identifier. (optional)
     * @param customerId Filter by customer identifier. (optional)
     * @param status Filter by order/payment status. (optional)
     * @param pageSize Size of a page, defaults to 10. Maximum is 100. (optional, default to 10)
     * @param pageNumber Page number, defaults to 1. (optional, default to 1)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> List of orders/payments retrieved successfully. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call ordersListAsync(String createdAtLte, String createdAtGte, String productId, String customerId, String status, BigDecimal pageSize, BigDecimal pageNumber, final ApiCallback<OrderList> _callback) throws ApiException {

        okhttp3.Call localVarCall = ordersListValidateBeforeCall(createdAtLte, createdAtGte, productId, customerId, status, pageSize, pageNumber, _callback);
        Type localVarReturnType = new TypeToken<OrderList>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for ordersUpdate
     * @param id The unique order/payment ID. (required)
     * @param orderUpdate  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Order billing address updated successfully. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call ordersUpdateCall(String id, OrderUpdate orderUpdate, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = orderUpdate;

        // create path and map variables
        String localVarPath = "/v1/orders/{id}"
            .replace("{" + "id" + "}", localVarApiClient.escapeString(id.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "ApiKeyAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "PATCH", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call ordersUpdateValidateBeforeCall(String id, OrderUpdate orderUpdate, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'id' is set
        if (id == null) {
            throw new ApiException("Missing the required parameter 'id' when calling ordersUpdate(Async)");
        }

        // verify the required parameter 'orderUpdate' is set
        if (orderUpdate == null) {
            throw new ApiException("Missing the required parameter 'orderUpdate' when calling ordersUpdate(Async)");
        }

        return ordersUpdateCall(id, orderUpdate, _callback);

    }

    /**
     * Update Order Billing Address
     * Update the billing details of an existing order.
     * @param id The unique order/payment ID. (required)
     * @param orderUpdate  (required)
     * @return Order
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Order billing address updated successfully. </td><td>  -  </td></tr>
     </table>
     */
    public Order ordersUpdate(String id, OrderUpdate orderUpdate) throws ApiException {
        ApiResponse<Order> localVarResp = ordersUpdateWithHttpInfo(id, orderUpdate);
        return localVarResp.getData();
    }

    /**
     * Update Order Billing Address
     * Update the billing details of an existing order.
     * @param id The unique order/payment ID. (required)
     * @param orderUpdate  (required)
     * @return ApiResponse&lt;Order&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Order billing address updated successfully. </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Order> ordersUpdateWithHttpInfo(String id, OrderUpdate orderUpdate) throws ApiException {
        okhttp3.Call localVarCall = ordersUpdateValidateBeforeCall(id, orderUpdate, null);
        Type localVarReturnType = new TypeToken<Order>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Update Order Billing Address (asynchronously)
     * Update the billing details of an existing order.
     * @param id The unique order/payment ID. (required)
     * @param orderUpdate  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Order billing address updated successfully. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call ordersUpdateAsync(String id, OrderUpdate orderUpdate, final ApiCallback<Order> _callback) throws ApiException {

        okhttp3.Call localVarCall = ordersUpdateValidateBeforeCall(id, orderUpdate, _callback);
        Type localVarReturnType = new TypeToken<Order>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for refundsCreate
     * @param id The unique order/payment ID. (required)
     * @param orderRefundCreate  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td> Refund processed successfully. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call refundsCreateCall(String id, OrderRefundCreate orderRefundCreate, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = orderRefundCreate;

        // create path and map variables
        String localVarPath = "/v1/orders/{id}/refund"
            .replace("{" + "id" + "}", localVarApiClient.escapeString(id.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "ApiKeyAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call refundsCreateValidateBeforeCall(String id, OrderRefundCreate orderRefundCreate, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'id' is set
        if (id == null) {
            throw new ApiException("Missing the required parameter 'id' when calling refundsCreate(Async)");
        }

        // verify the required parameter 'orderRefundCreate' is set
        if (orderRefundCreate == null) {
            throw new ApiException("Missing the required parameter 'orderRefundCreate' when calling refundsCreate(Async)");
        }

        return refundsCreateCall(id, orderRefundCreate, _callback);

    }

    /**
     * Create Refund
     * Initiate a full or partial refund for a specific payment/order.
     * @param id The unique order/payment ID. (required)
     * @param orderRefundCreate  (required)
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td> Refund processed successfully. </td><td>  -  </td></tr>
     </table>
     */
    public void refundsCreate(String id, OrderRefundCreate orderRefundCreate) throws ApiException {
        refundsCreateWithHttpInfo(id, orderRefundCreate);
    }

    /**
     * Create Refund
     * Initiate a full or partial refund for a specific payment/order.
     * @param id The unique order/payment ID. (required)
     * @param orderRefundCreate  (required)
     * @return ApiResponse&lt;Void&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td> Refund processed successfully. </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Void> refundsCreateWithHttpInfo(String id, OrderRefundCreate orderRefundCreate) throws ApiException {
        okhttp3.Call localVarCall = refundsCreateValidateBeforeCall(id, orderRefundCreate, null);
        return localVarApiClient.execute(localVarCall);
    }

    /**
     * Create Refund (asynchronously)
     * Initiate a full or partial refund for a specific payment/order.
     * @param id The unique order/payment ID. (required)
     * @param orderRefundCreate  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td> Refund processed successfully. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call refundsCreateAsync(String id, OrderRefundCreate orderRefundCreate, final ApiCallback<Void> _callback) throws ApiException {

        okhttp3.Call localVarCall = refundsCreateValidateBeforeCall(id, orderRefundCreate, _callback);
        localVarApiClient.executeAsync(localVarCall, _callback);
        return localVarCall;
    }
}
