/*
 * Solifyn API
 * Welcome to the Solifyn API Reference. Leverage our secure endpoints to manage products and issue, validate, and manage software license keys programmatically.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.solifyn.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.solifyn.model.MeterQuantitiesCostDto;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.solifyn.JSON;

/**
 * Represents aggregated usage quantities and calculated product costs for a meter within a selected date range.
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-06-04T06:44:41.869456600+07:00[Asia/Saigon]", comments = "Generator version: 7.10.0")
public class MeterQuantitiesResponseDto {
  public static final String SERIALIZED_NAME_METER_ID = "meterId";
  @SerializedName(SERIALIZED_NAME_METER_ID)
  @javax.annotation.Nonnull
  private String meterId;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  @javax.annotation.Nonnull
  private String name;

  public static final String SERIALIZED_NAME_TOTAL_USAGE = "totalUsage";
  @SerializedName(SERIALIZED_NAME_TOTAL_USAGE)
  @javax.annotation.Nonnull
  private BigDecimal totalUsage;

  public static final String SERIALIZED_NAME_COSTS = "costs";
  @SerializedName(SERIALIZED_NAME_COSTS)
  @javax.annotation.Nonnull
  private List<MeterQuantitiesCostDto> costs = new ArrayList<>();

  public MeterQuantitiesResponseDto() {
  }

  public MeterQuantitiesResponseDto meterId(@javax.annotation.Nonnull String meterId) {
    this.meterId = meterId;
    return this;
  }

  /**
   * The unique meter ID.
   * @return meterId
   */
  @javax.annotation.Nonnull
  public String getMeterId() {
    return meterId;
  }

  public void setMeterId(@javax.annotation.Nonnull String meterId) {
    this.meterId = meterId;
  }


  public MeterQuantitiesResponseDto name(@javax.annotation.Nonnull String name) {
    this.name = name;
    return this;
  }

  /**
   * Meter display name.
   * @return name
   */
  @javax.annotation.Nonnull
  public String getName() {
    return name;
  }

  public void setName(@javax.annotation.Nonnull String name) {
    this.name = name;
  }


  public MeterQuantitiesResponseDto totalUsage(@javax.annotation.Nonnull BigDecimal totalUsage) {
    this.totalUsage = totalUsage;
    return this;
  }

  /**
   * Total usage within the selected time range.
   * @return totalUsage
   */
  @javax.annotation.Nonnull
  public BigDecimal getTotalUsage() {
    return totalUsage;
  }

  public void setTotalUsage(@javax.annotation.Nonnull BigDecimal totalUsage) {
    this.totalUsage = totalUsage;
  }


  public MeterQuantitiesResponseDto costs(@javax.annotation.Nonnull List<MeterQuantitiesCostDto> costs) {
    this.costs = costs;
    return this;
  }

  public MeterQuantitiesResponseDto addCostsItem(MeterQuantitiesCostDto costsItem) {
    if (this.costs == null) {
      this.costs = new ArrayList<>();
    }
    this.costs.add(costsItem);
    return this;
  }

  /**
   * Cost breakdown for products attached to the meter.
   * @return costs
   */
  @javax.annotation.Nonnull
  public List<MeterQuantitiesCostDto> getCosts() {
    return costs;
  }

  public void setCosts(@javax.annotation.Nonnull List<MeterQuantitiesCostDto> costs) {
    this.costs = costs;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MeterQuantitiesResponseDto meterQuantitiesResponseDto = (MeterQuantitiesResponseDto) o;
    return Objects.equals(this.meterId, meterQuantitiesResponseDto.meterId) &&
        Objects.equals(this.name, meterQuantitiesResponseDto.name) &&
        Objects.equals(this.totalUsage, meterQuantitiesResponseDto.totalUsage) &&
        Objects.equals(this.costs, meterQuantitiesResponseDto.costs);
  }

  @Override
  public int hashCode() {
    return Objects.hash(meterId, name, totalUsage, costs);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MeterQuantitiesResponseDto {\n");
    sb.append("    meterId: ").append(toIndentedString(meterId)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    totalUsage: ").append(toIndentedString(totalUsage)).append("\n");
    sb.append("    costs: ").append(toIndentedString(costs)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("meterId");
    openapiFields.add("name");
    openapiFields.add("totalUsage");
    openapiFields.add("costs");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("meterId");
    openapiRequiredFields.add("name");
    openapiRequiredFields.add("totalUsage");
    openapiRequiredFields.add("costs");
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to MeterQuantitiesResponseDto
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!MeterQuantitiesResponseDto.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in MeterQuantitiesResponseDto is not found in the empty JSON string", MeterQuantitiesResponseDto.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!MeterQuantitiesResponseDto.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `MeterQuantitiesResponseDto` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : MeterQuantitiesResponseDto.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("meterId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `meterId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("meterId").toString()));
      }
      if (!jsonObj.get("name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("name").toString()));
      }
      // ensure the json data is an array
      if (!jsonObj.get("costs").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `costs` to be an array in the JSON string but got `%s`", jsonObj.get("costs").toString()));
      }

      JsonArray jsonArraycosts = jsonObj.getAsJsonArray("costs");
      // validate the required field `costs` (array)
      for (int i = 0; i < jsonArraycosts.size(); i++) {
        MeterQuantitiesCostDto.validateJsonElement(jsonArraycosts.get(i));
      };
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!MeterQuantitiesResponseDto.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'MeterQuantitiesResponseDto' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<MeterQuantitiesResponseDto> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(MeterQuantitiesResponseDto.class));

       return (TypeAdapter<T>) new TypeAdapter<MeterQuantitiesResponseDto>() {
           @Override
           public void write(JsonWriter out, MeterQuantitiesResponseDto value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public MeterQuantitiesResponseDto read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of MeterQuantitiesResponseDto given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of MeterQuantitiesResponseDto
   * @throws IOException if the JSON string is invalid with respect to MeterQuantitiesResponseDto
   */
  public static MeterQuantitiesResponseDto fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, MeterQuantitiesResponseDto.class);
  }

  /**
   * Convert an instance of MeterQuantitiesResponseDto to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

