/*
 * Solifyn API
 * Welcome to the Solifyn API Reference. Leverage our secure endpoints to manage products and issue, validate, and manage software license keys programmatically.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.solifyn.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.solifyn.model.MeterUsageEventDto;
import java.io.IOException;
import java.math.BigDecimal;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.openapitools.jackson.nullable.JsonNullable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.solifyn.JSON;

/**
 * Represents a usage meter with its most recent usage events and total usage event count.
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-06-10T11:03:57.669874500+07:00[Asia/Saigon]", comments = "Generator version: 7.10.0")
public class MeterDetailResponseDto {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  @javax.annotation.Nonnull
  private String id;

  public static final String SERIALIZED_NAME_BUSINESS_ID = "businessId";
  @SerializedName(SERIALIZED_NAME_BUSINESS_ID)
  @javax.annotation.Nonnull
  private String businessId;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  @javax.annotation.Nonnull
  private String name;

  public static final String SERIALIZED_NAME_DESCRIPTION = "description";
  @SerializedName(SERIALIZED_NAME_DESCRIPTION)
  @javax.annotation.Nullable
  private Object description;

  public static final String SERIALIZED_NAME_EVENT_NAME = "eventName";
  @SerializedName(SERIALIZED_NAME_EVENT_NAME)
  @javax.annotation.Nonnull
  private String eventName;

  /**
   * Aggregation strategy for usage events.
   */
  @JsonAdapter(AggregationTypeEnum.Adapter.class)
  public enum AggregationTypeEnum {
    COUNT("COUNT"),
    
    SUM("SUM"),
    
    MAX("MAX"),
    
    LAST("LAST");

    private String value;

    AggregationTypeEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static AggregationTypeEnum fromValue(String value) {
      for (AggregationTypeEnum b : AggregationTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<AggregationTypeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final AggregationTypeEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public AggregationTypeEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return AggregationTypeEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      AggregationTypeEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_AGGREGATION_TYPE = "aggregationType";
  @SerializedName(SERIALIZED_NAME_AGGREGATION_TYPE)
  @javax.annotation.Nonnull
  private AggregationTypeEnum aggregationType;

  public static final String SERIALIZED_NAME_AGGREGATION_KEY = "aggregationKey";
  @SerializedName(SERIALIZED_NAME_AGGREGATION_KEY)
  @javax.annotation.Nullable
  private Object aggregationKey;

  public static final String SERIALIZED_NAME_UNIT = "unit";
  @SerializedName(SERIALIZED_NAME_UNIT)
  @javax.annotation.Nullable
  private Object unit;

  public static final String SERIALIZED_NAME_FILTERS = "filters";
  @SerializedName(SERIALIZED_NAME_FILTERS)
  @javax.annotation.Nullable
  private Map<String, Object> filters;

  public static final String SERIALIZED_NAME_ARCHIVED = "archived";
  @SerializedName(SERIALIZED_NAME_ARCHIVED)
  @javax.annotation.Nonnull
  private Boolean archived;

  public static final String SERIALIZED_NAME_CREATED_AT = "createdAt";
  @SerializedName(SERIALIZED_NAME_CREATED_AT)
  @javax.annotation.Nonnull
  private OffsetDateTime createdAt;

  public static final String SERIALIZED_NAME_UPDATED_AT = "updatedAt";
  @SerializedName(SERIALIZED_NAME_UPDATED_AT)
  @javax.annotation.Nonnull
  private OffsetDateTime updatedAt;

  public static final String SERIALIZED_NAME_USAGE_EVENTS = "usageEvents";
  @SerializedName(SERIALIZED_NAME_USAGE_EVENTS)
  @javax.annotation.Nonnull
  private List<MeterUsageEventDto> usageEvents = new ArrayList<>();

  public static final String SERIALIZED_NAME_TOTAL_USAGE_EVENTS = "totalUsageEvents";
  @SerializedName(SERIALIZED_NAME_TOTAL_USAGE_EVENTS)
  @javax.annotation.Nonnull
  private BigDecimal totalUsageEvents;

  public MeterDetailResponseDto() {
  }

  public MeterDetailResponseDto id(@javax.annotation.Nonnull String id) {
    this.id = id;
    return this;
  }

  /**
   * The unique meter ID.
   * @return id
   */
  @javax.annotation.Nonnull
  public String getId() {
    return id;
  }

  public void setId(@javax.annotation.Nonnull String id) {
    this.id = id;
  }


  public MeterDetailResponseDto businessId(@javax.annotation.Nonnull String businessId) {
    this.businessId = businessId;
    return this;
  }

  /**
   * The business ID that owns this meter.
   * @return businessId
   */
  @javax.annotation.Nonnull
  public String getBusinessId() {
    return businessId;
  }

  public void setBusinessId(@javax.annotation.Nonnull String businessId) {
    this.businessId = businessId;
  }


  public MeterDetailResponseDto name(@javax.annotation.Nonnull String name) {
    this.name = name;
    return this;
  }

  /**
   * Meter display name.
   * @return name
   */
  @javax.annotation.Nonnull
  public String getName() {
    return name;
  }

  public void setName(@javax.annotation.Nonnull String name) {
    this.name = name;
  }


  public MeterDetailResponseDto description(@javax.annotation.Nullable Object description) {
    this.description = description;
    return this;
  }

  /**
   * Meter description.
   * @return description
   */
  @javax.annotation.Nullable
  public Object getDescription() {
    return description;
  }

  public void setDescription(@javax.annotation.Nullable Object description) {
    this.description = description;
  }


  public MeterDetailResponseDto eventName(@javax.annotation.Nonnull String eventName) {
    this.eventName = eventName;
    return this;
  }

  /**
   * The event name tracked by this meter.
   * @return eventName
   */
  @javax.annotation.Nonnull
  public String getEventName() {
    return eventName;
  }

  public void setEventName(@javax.annotation.Nonnull String eventName) {
    this.eventName = eventName;
  }


  public MeterDetailResponseDto aggregationType(@javax.annotation.Nonnull AggregationTypeEnum aggregationType) {
    this.aggregationType = aggregationType;
    return this;
  }

  /**
   * Aggregation strategy for usage events.
   * @return aggregationType
   */
  @javax.annotation.Nonnull
  public AggregationTypeEnum getAggregationType() {
    return aggregationType;
  }

  public void setAggregationType(@javax.annotation.Nonnull AggregationTypeEnum aggregationType) {
    this.aggregationType = aggregationType;
  }


  public MeterDetailResponseDto aggregationKey(@javax.annotation.Nullable Object aggregationKey) {
    this.aggregationKey = aggregationKey;
    return this;
  }

  /**
   * Metadata key used for aggregation.
   * @return aggregationKey
   */
  @javax.annotation.Nullable
  public Object getAggregationKey() {
    return aggregationKey;
  }

  public void setAggregationKey(@javax.annotation.Nullable Object aggregationKey) {
    this.aggregationKey = aggregationKey;
  }


  public MeterDetailResponseDto unit(@javax.annotation.Nullable Object unit) {
    this.unit = unit;
    return this;
  }

  /**
   * Measurement unit label.
   * @return unit
   */
  @javax.annotation.Nullable
  public Object getUnit() {
    return unit;
  }

  public void setUnit(@javax.annotation.Nullable Object unit) {
    this.unit = unit;
  }


  public MeterDetailResponseDto filters(@javax.annotation.Nullable Map<String, Object> filters) {
    this.filters = filters;
    return this;
  }

  public MeterDetailResponseDto putFiltersItem(String key, Object filtersItem) {
    if (this.filters == null) {
      this.filters = new HashMap<>();
    }
    this.filters.put(key, filtersItem);
    return this;
  }

  /**
   * Optional filter definition for advanced matching.
   * @return filters
   */
  @javax.annotation.Nullable
  public Map<String, Object> getFilters() {
    return filters;
  }

  public void setFilters(@javax.annotation.Nullable Map<String, Object> filters) {
    this.filters = filters;
  }


  public MeterDetailResponseDto archived(@javax.annotation.Nonnull Boolean archived) {
    this.archived = archived;
    return this;
  }

  /**
   * Whether the meter is archived.
   * @return archived
   */
  @javax.annotation.Nonnull
  public Boolean getArchived() {
    return archived;
  }

  public void setArchived(@javax.annotation.Nonnull Boolean archived) {
    this.archived = archived;
  }


  public MeterDetailResponseDto createdAt(@javax.annotation.Nonnull OffsetDateTime createdAt) {
    this.createdAt = createdAt;
    return this;
  }

  /**
   * Creation timestamp.
   * @return createdAt
   */
  @javax.annotation.Nonnull
  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(@javax.annotation.Nonnull OffsetDateTime createdAt) {
    this.createdAt = createdAt;
  }


  public MeterDetailResponseDto updatedAt(@javax.annotation.Nonnull OffsetDateTime updatedAt) {
    this.updatedAt = updatedAt;
    return this;
  }

  /**
   * Last update timestamp.
   * @return updatedAt
   */
  @javax.annotation.Nonnull
  public OffsetDateTime getUpdatedAt() {
    return updatedAt;
  }

  public void setUpdatedAt(@javax.annotation.Nonnull OffsetDateTime updatedAt) {
    this.updatedAt = updatedAt;
  }


  public MeterDetailResponseDto usageEvents(@javax.annotation.Nonnull List<MeterUsageEventDto> usageEvents) {
    this.usageEvents = usageEvents;
    return this;
  }

  public MeterDetailResponseDto addUsageEventsItem(MeterUsageEventDto usageEventsItem) {
    if (this.usageEvents == null) {
      this.usageEvents = new ArrayList<>();
    }
    this.usageEvents.add(usageEventsItem);
    return this;
  }

  /**
   * Most recent usage events recorded for the meter.
   * @return usageEvents
   */
  @javax.annotation.Nonnull
  public List<MeterUsageEventDto> getUsageEvents() {
    return usageEvents;
  }

  public void setUsageEvents(@javax.annotation.Nonnull List<MeterUsageEventDto> usageEvents) {
    this.usageEvents = usageEvents;
  }


  public MeterDetailResponseDto totalUsageEvents(@javax.annotation.Nonnull BigDecimal totalUsageEvents) {
    this.totalUsageEvents = totalUsageEvents;
    return this;
  }

  /**
   * Total usage event count for the meter.
   * @return totalUsageEvents
   */
  @javax.annotation.Nonnull
  public BigDecimal getTotalUsageEvents() {
    return totalUsageEvents;
  }

  public void setTotalUsageEvents(@javax.annotation.Nonnull BigDecimal totalUsageEvents) {
    this.totalUsageEvents = totalUsageEvents;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MeterDetailResponseDto meterDetailResponseDto = (MeterDetailResponseDto) o;
    return Objects.equals(this.id, meterDetailResponseDto.id) &&
        Objects.equals(this.businessId, meterDetailResponseDto.businessId) &&
        Objects.equals(this.name, meterDetailResponseDto.name) &&
        Objects.equals(this.description, meterDetailResponseDto.description) &&
        Objects.equals(this.eventName, meterDetailResponseDto.eventName) &&
        Objects.equals(this.aggregationType, meterDetailResponseDto.aggregationType) &&
        Objects.equals(this.aggregationKey, meterDetailResponseDto.aggregationKey) &&
        Objects.equals(this.unit, meterDetailResponseDto.unit) &&
        Objects.equals(this.filters, meterDetailResponseDto.filters) &&
        Objects.equals(this.archived, meterDetailResponseDto.archived) &&
        Objects.equals(this.createdAt, meterDetailResponseDto.createdAt) &&
        Objects.equals(this.updatedAt, meterDetailResponseDto.updatedAt) &&
        Objects.equals(this.usageEvents, meterDetailResponseDto.usageEvents) &&
        Objects.equals(this.totalUsageEvents, meterDetailResponseDto.totalUsageEvents);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, businessId, name, description, eventName, aggregationType, aggregationKey, unit, filters, archived, createdAt, updatedAt, usageEvents, totalUsageEvents);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MeterDetailResponseDto {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    businessId: ").append(toIndentedString(businessId)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    eventName: ").append(toIndentedString(eventName)).append("\n");
    sb.append("    aggregationType: ").append(toIndentedString(aggregationType)).append("\n");
    sb.append("    aggregationKey: ").append(toIndentedString(aggregationKey)).append("\n");
    sb.append("    unit: ").append(toIndentedString(unit)).append("\n");
    sb.append("    filters: ").append(toIndentedString(filters)).append("\n");
    sb.append("    archived: ").append(toIndentedString(archived)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("    usageEvents: ").append(toIndentedString(usageEvents)).append("\n");
    sb.append("    totalUsageEvents: ").append(toIndentedString(totalUsageEvents)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("id");
    openapiFields.add("businessId");
    openapiFields.add("name");
    openapiFields.add("description");
    openapiFields.add("eventName");
    openapiFields.add("aggregationType");
    openapiFields.add("aggregationKey");
    openapiFields.add("unit");
    openapiFields.add("filters");
    openapiFields.add("archived");
    openapiFields.add("createdAt");
    openapiFields.add("updatedAt");
    openapiFields.add("usageEvents");
    openapiFields.add("totalUsageEvents");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("id");
    openapiRequiredFields.add("businessId");
    openapiRequiredFields.add("name");
    openapiRequiredFields.add("eventName");
    openapiRequiredFields.add("aggregationType");
    openapiRequiredFields.add("archived");
    openapiRequiredFields.add("createdAt");
    openapiRequiredFields.add("updatedAt");
    openapiRequiredFields.add("usageEvents");
    openapiRequiredFields.add("totalUsageEvents");
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to MeterDetailResponseDto
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!MeterDetailResponseDto.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in MeterDetailResponseDto is not found in the empty JSON string", MeterDetailResponseDto.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!MeterDetailResponseDto.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `MeterDetailResponseDto` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : MeterDetailResponseDto.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("id").toString()));
      }
      if (!jsonObj.get("businessId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `businessId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("businessId").toString()));
      }
      if (!jsonObj.get("name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("name").toString()));
      }
      if (!jsonObj.get("eventName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `eventName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("eventName").toString()));
      }
      if (!jsonObj.get("aggregationType").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `aggregationType` to be a primitive type in the JSON string but got `%s`", jsonObj.get("aggregationType").toString()));
      }
      // validate the required field `aggregationType`
      AggregationTypeEnum.validateJsonElement(jsonObj.get("aggregationType"));
      // ensure the json data is an array
      if (!jsonObj.get("usageEvents").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `usageEvents` to be an array in the JSON string but got `%s`", jsonObj.get("usageEvents").toString()));
      }

      JsonArray jsonArrayusageEvents = jsonObj.getAsJsonArray("usageEvents");
      // validate the required field `usageEvents` (array)
      for (int i = 0; i < jsonArrayusageEvents.size(); i++) {
        MeterUsageEventDto.validateJsonElement(jsonArrayusageEvents.get(i));
      };
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!MeterDetailResponseDto.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'MeterDetailResponseDto' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<MeterDetailResponseDto> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(MeterDetailResponseDto.class));

       return (TypeAdapter<T>) new TypeAdapter<MeterDetailResponseDto>() {
           @Override
           public void write(JsonWriter out, MeterDetailResponseDto value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public MeterDetailResponseDto read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of MeterDetailResponseDto given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of MeterDetailResponseDto
   * @throws IOException if the JSON string is invalid with respect to MeterDetailResponseDto
   */
  public static MeterDetailResponseDto fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, MeterDetailResponseDto.class);
  }

  /**
   * Convert an instance of MeterDetailResponseDto to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

