/*
 * Solifyn API
 * Welcome to the Solifyn API Reference. Leverage our secure endpoints to manage products and issue, validate, and manage software license keys programmatically.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.solifyn.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.solifyn.JSON;

/**
 * SubscriptionAction
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-06-10T10:35:18.867171700+07:00[Asia/Saigon]", comments = "Generator version: 7.10.0")
public class SubscriptionAction {
  public static final String SERIALIZED_NAME_FREE_DAYS = "free_days";
  @SerializedName(SERIALIZED_NAME_FREE_DAYS)
  @javax.annotation.Nullable
  private BigDecimal freeDays;

  /**
   * Cancellation mode (used with action: cancel)
   */
  @JsonAdapter(CancellationModeEnum.Adapter.class)
  public enum CancellationModeEnum {
    IMMEDIATE("immediate"),
    
    AT_PERIOD_END("at_period_end");

    private String value;

    CancellationModeEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static CancellationModeEnum fromValue(String value) {
      for (CancellationModeEnum b : CancellationModeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<CancellationModeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final CancellationModeEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public CancellationModeEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return CancellationModeEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      CancellationModeEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_CANCELLATION_MODE = "cancellation_mode";
  @SerializedName(SERIALIZED_NAME_CANCELLATION_MODE)
  @javax.annotation.Nullable
  private CancellationModeEnum cancellationMode;

  public static final String SERIALIZED_NAME_VOID_PAYMENTS = "void_payments";
  @SerializedName(SERIALIZED_NAME_VOID_PAYMENTS)
  @javax.annotation.Nullable
  private Boolean voidPayments;

  public static final String SERIALIZED_NAME_ADDON_PRODUCT_ID = "addonProductId";
  @SerializedName(SERIALIZED_NAME_ADDON_PRODUCT_ID)
  @javax.annotation.Nullable
  private String addonProductId;

  public static final String SERIALIZED_NAME_NEW_QUANTITY = "newQuantity";
  @SerializedName(SERIALIZED_NAME_NEW_QUANTITY)
  @javax.annotation.Nullable
  private BigDecimal newQuantity;

  /**
   * Proration strategy mode (used with action: adjust_seats)
   */
  @JsonAdapter(ProrationTypeEnum.Adapter.class)
  public enum ProrationTypeEnum {
    PRORATED_IMMEDIATELY("prorated_immediately"),
    
    FULL_IMMEDIATELY("full_immediately"),
    
    DIFFERENCE_IMMEDIATELY("difference_immediately"),
    
    DO_NOT_BILL("do_not_bill");

    private String value;

    ProrationTypeEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static ProrationTypeEnum fromValue(String value) {
      for (ProrationTypeEnum b : ProrationTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<ProrationTypeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final ProrationTypeEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public ProrationTypeEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return ProrationTypeEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      ProrationTypeEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_PRORATION_TYPE = "prorationType";
  @SerializedName(SERIALIZED_NAME_PRORATION_TYPE)
  @javax.annotation.Nullable
  private ProrationTypeEnum prorationType;

  public static final String SERIALIZED_NAME_IDEMPOTENCY_KEY = "idempotencyKey";
  @SerializedName(SERIALIZED_NAME_IDEMPOTENCY_KEY)
  @javax.annotation.Nullable
  private String idempotencyKey;

  public SubscriptionAction() {
  }

  public SubscriptionAction freeDays(@javax.annotation.Nullable BigDecimal freeDays) {
    this.freeDays = freeDays;
    return this;
  }

  /**
   * Number of free days to add (used with action: add_free_days)
   * minimum: 1
   * maximum: 3650
   * @return freeDays
   */
  @javax.annotation.Nullable
  public BigDecimal getFreeDays() {
    return freeDays;
  }

  public void setFreeDays(@javax.annotation.Nullable BigDecimal freeDays) {
    this.freeDays = freeDays;
  }


  public SubscriptionAction cancellationMode(@javax.annotation.Nullable CancellationModeEnum cancellationMode) {
    this.cancellationMode = cancellationMode;
    return this;
  }

  /**
   * Cancellation mode (used with action: cancel)
   * @return cancellationMode
   */
  @javax.annotation.Nullable
  public CancellationModeEnum getCancellationMode() {
    return cancellationMode;
  }

  public void setCancellationMode(@javax.annotation.Nullable CancellationModeEnum cancellationMode) {
    this.cancellationMode = cancellationMode;
  }


  public SubscriptionAction voidPayments(@javax.annotation.Nullable Boolean voidPayments) {
    this.voidPayments = voidPayments;
    return this;
  }

  /**
   * Whether to void subsequent payments (used with action: pause)
   * @return voidPayments
   */
  @javax.annotation.Nullable
  public Boolean getVoidPayments() {
    return voidPayments;
  }

  public void setVoidPayments(@javax.annotation.Nullable Boolean voidPayments) {
    this.voidPayments = voidPayments;
  }


  public SubscriptionAction addonProductId(@javax.annotation.Nullable String addonProductId) {
    this.addonProductId = addonProductId;
    return this;
  }

  /**
   * ID of the addon product to adjust seats for (used with action: adjust_seats)
   * @return addonProductId
   */
  @javax.annotation.Nullable
  public String getAddonProductId() {
    return addonProductId;
  }

  public void setAddonProductId(@javax.annotation.Nullable String addonProductId) {
    this.addonProductId = addonProductId;
  }


  public SubscriptionAction newQuantity(@javax.annotation.Nullable BigDecimal newQuantity) {
    this.newQuantity = newQuantity;
    return this;
  }

  /**
   * The new seat quantity (used with action: adjust_seats)
   * minimum: 0
   * @return newQuantity
   */
  @javax.annotation.Nullable
  public BigDecimal getNewQuantity() {
    return newQuantity;
  }

  public void setNewQuantity(@javax.annotation.Nullable BigDecimal newQuantity) {
    this.newQuantity = newQuantity;
  }


  public SubscriptionAction prorationType(@javax.annotation.Nullable ProrationTypeEnum prorationType) {
    this.prorationType = prorationType;
    return this;
  }

  /**
   * Proration strategy mode (used with action: adjust_seats)
   * @return prorationType
   */
  @javax.annotation.Nullable
  public ProrationTypeEnum getProrationType() {
    return prorationType;
  }

  public void setProrationType(@javax.annotation.Nullable ProrationTypeEnum prorationType) {
    this.prorationType = prorationType;
  }


  public SubscriptionAction idempotencyKey(@javax.annotation.Nullable String idempotencyKey) {
    this.idempotencyKey = idempotencyKey;
    return this;
  }

  /**
   * A unique idempotency key to prevent duplicate mutative actions for network transient retries.
   * @return idempotencyKey
   */
  @javax.annotation.Nullable
  public String getIdempotencyKey() {
    return idempotencyKey;
  }

  public void setIdempotencyKey(@javax.annotation.Nullable String idempotencyKey) {
    this.idempotencyKey = idempotencyKey;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SubscriptionAction subscriptionAction = (SubscriptionAction) o;
    return Objects.equals(this.freeDays, subscriptionAction.freeDays) &&
        Objects.equals(this.cancellationMode, subscriptionAction.cancellationMode) &&
        Objects.equals(this.voidPayments, subscriptionAction.voidPayments) &&
        Objects.equals(this.addonProductId, subscriptionAction.addonProductId) &&
        Objects.equals(this.newQuantity, subscriptionAction.newQuantity) &&
        Objects.equals(this.prorationType, subscriptionAction.prorationType) &&
        Objects.equals(this.idempotencyKey, subscriptionAction.idempotencyKey);
  }

  @Override
  public int hashCode() {
    return Objects.hash(freeDays, cancellationMode, voidPayments, addonProductId, newQuantity, prorationType, idempotencyKey);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SubscriptionAction {\n");
    sb.append("    freeDays: ").append(toIndentedString(freeDays)).append("\n");
    sb.append("    cancellationMode: ").append(toIndentedString(cancellationMode)).append("\n");
    sb.append("    voidPayments: ").append(toIndentedString(voidPayments)).append("\n");
    sb.append("    addonProductId: ").append(toIndentedString(addonProductId)).append("\n");
    sb.append("    newQuantity: ").append(toIndentedString(newQuantity)).append("\n");
    sb.append("    prorationType: ").append(toIndentedString(prorationType)).append("\n");
    sb.append("    idempotencyKey: ").append(toIndentedString(idempotencyKey)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("free_days");
    openapiFields.add("cancellation_mode");
    openapiFields.add("void_payments");
    openapiFields.add("addonProductId");
    openapiFields.add("newQuantity");
    openapiFields.add("prorationType");
    openapiFields.add("idempotencyKey");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to SubscriptionAction
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!SubscriptionAction.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in SubscriptionAction is not found in the empty JSON string", SubscriptionAction.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!SubscriptionAction.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `SubscriptionAction` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("cancellation_mode") != null && !jsonObj.get("cancellation_mode").isJsonNull()) && !jsonObj.get("cancellation_mode").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `cancellation_mode` to be a primitive type in the JSON string but got `%s`", jsonObj.get("cancellation_mode").toString()));
      }
      // validate the optional field `cancellation_mode`
      if (jsonObj.get("cancellation_mode") != null && !jsonObj.get("cancellation_mode").isJsonNull()) {
        CancellationModeEnum.validateJsonElement(jsonObj.get("cancellation_mode"));
      }
      if ((jsonObj.get("addonProductId") != null && !jsonObj.get("addonProductId").isJsonNull()) && !jsonObj.get("addonProductId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `addonProductId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("addonProductId").toString()));
      }
      if ((jsonObj.get("prorationType") != null && !jsonObj.get("prorationType").isJsonNull()) && !jsonObj.get("prorationType").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `prorationType` to be a primitive type in the JSON string but got `%s`", jsonObj.get("prorationType").toString()));
      }
      // validate the optional field `prorationType`
      if (jsonObj.get("prorationType") != null && !jsonObj.get("prorationType").isJsonNull()) {
        ProrationTypeEnum.validateJsonElement(jsonObj.get("prorationType"));
      }
      if ((jsonObj.get("idempotencyKey") != null && !jsonObj.get("idempotencyKey").isJsonNull()) && !jsonObj.get("idempotencyKey").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `idempotencyKey` to be a primitive type in the JSON string but got `%s`", jsonObj.get("idempotencyKey").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!SubscriptionAction.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'SubscriptionAction' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<SubscriptionAction> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(SubscriptionAction.class));

       return (TypeAdapter<T>) new TypeAdapter<SubscriptionAction>() {
           @Override
           public void write(JsonWriter out, SubscriptionAction value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public SubscriptionAction read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of SubscriptionAction given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of SubscriptionAction
   * @throws IOException if the JSON string is invalid with respect to SubscriptionAction
   */
  public static SubscriptionAction fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, SubscriptionAction.class);
  }

  /**
   * Convert an instance of SubscriptionAction to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

