/*
 * Solifyn API
 * Welcome to the Solifyn API Reference. Leverage our secure endpoints to manage products and issue, validate, and manage software license keys programmatically.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.solifyn.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import java.util.HashMap;
import java.util.Map;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.solifyn.JSON;

/**
 * UpdateMeterDto
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-06-11T08:41:07.343307200+07:00[Asia/Saigon]", comments = "Generator version: 7.10.0")
public class UpdateMeterDto {
  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  @javax.annotation.Nullable
  private String name;

  public static final String SERIALIZED_NAME_DESCRIPTION = "description";
  @SerializedName(SERIALIZED_NAME_DESCRIPTION)
  @javax.annotation.Nullable
  private String description;

  public static final String SERIALIZED_NAME_EVENT_NAME = "eventName";
  @SerializedName(SERIALIZED_NAME_EVENT_NAME)
  @javax.annotation.Nullable
  private String eventName;

  /**
   * Aggregation strategy for usage events.
   */
  @JsonAdapter(AggregationTypeEnum.Adapter.class)
  public enum AggregationTypeEnum {
    COUNT("COUNT"),
    
    SUM("SUM"),
    
    MAX("MAX"),
    
    LAST("LAST");

    private String value;

    AggregationTypeEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static AggregationTypeEnum fromValue(String value) {
      for (AggregationTypeEnum b : AggregationTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<AggregationTypeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final AggregationTypeEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public AggregationTypeEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return AggregationTypeEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      AggregationTypeEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_AGGREGATION_TYPE = "aggregationType";
  @SerializedName(SERIALIZED_NAME_AGGREGATION_TYPE)
  @javax.annotation.Nullable
  private AggregationTypeEnum aggregationType;

  public static final String SERIALIZED_NAME_AGGREGATION_KEY = "aggregationKey";
  @SerializedName(SERIALIZED_NAME_AGGREGATION_KEY)
  @javax.annotation.Nullable
  private String aggregationKey;

  public static final String SERIALIZED_NAME_UNIT = "unit";
  @SerializedName(SERIALIZED_NAME_UNIT)
  @javax.annotation.Nullable
  private String unit;

  public static final String SERIALIZED_NAME_FILTERS = "filters";
  @SerializedName(SERIALIZED_NAME_FILTERS)
  @javax.annotation.Nullable
  private Map<String, Object> filters = new HashMap<>();

  public static final String SERIALIZED_NAME_ENABLE_FILTERING = "enableFiltering";
  @SerializedName(SERIALIZED_NAME_ENABLE_FILTERING)
  @javax.annotation.Nullable
  private Boolean enableFiltering;

  public UpdateMeterDto() {
  }

  public UpdateMeterDto name(@javax.annotation.Nullable String name) {
    this.name = name;
    return this;
  }

  /**
   * Meter display name.
   * @return name
   */
  @javax.annotation.Nullable
  public String getName() {
    return name;
  }

  public void setName(@javax.annotation.Nullable String name) {
    this.name = name;
  }


  public UpdateMeterDto description(@javax.annotation.Nullable String description) {
    this.description = description;
    return this;
  }

  /**
   * Meter description.
   * @return description
   */
  @javax.annotation.Nullable
  public String getDescription() {
    return description;
  }

  public void setDescription(@javax.annotation.Nullable String description) {
    this.description = description;
  }


  public UpdateMeterDto eventName(@javax.annotation.Nullable String eventName) {
    this.eventName = eventName;
    return this;
  }

  /**
   * The event name tracked by this meter.
   * @return eventName
   */
  @javax.annotation.Nullable
  public String getEventName() {
    return eventName;
  }

  public void setEventName(@javax.annotation.Nullable String eventName) {
    this.eventName = eventName;
  }


  public UpdateMeterDto aggregationType(@javax.annotation.Nullable AggregationTypeEnum aggregationType) {
    this.aggregationType = aggregationType;
    return this;
  }

  /**
   * Aggregation strategy for usage events.
   * @return aggregationType
   */
  @javax.annotation.Nullable
  public AggregationTypeEnum getAggregationType() {
    return aggregationType;
  }

  public void setAggregationType(@javax.annotation.Nullable AggregationTypeEnum aggregationType) {
    this.aggregationType = aggregationType;
  }


  public UpdateMeterDto aggregationKey(@javax.annotation.Nullable String aggregationKey) {
    this.aggregationKey = aggregationKey;
    return this;
  }

  /**
   * Metadata key used by SUM, MAX, or LAST aggregation modes.
   * @return aggregationKey
   */
  @javax.annotation.Nullable
  public String getAggregationKey() {
    return aggregationKey;
  }

  public void setAggregationKey(@javax.annotation.Nullable String aggregationKey) {
    this.aggregationKey = aggregationKey;
  }


  public UpdateMeterDto unit(@javax.annotation.Nullable String unit) {
    this.unit = unit;
    return this;
  }

  /**
   * Measurement unit label.
   * @return unit
   */
  @javax.annotation.Nullable
  public String getUnit() {
    return unit;
  }

  public void setUnit(@javax.annotation.Nullable String unit) {
    this.unit = unit;
  }


  public UpdateMeterDto filters(@javax.annotation.Nullable Map<String, Object> filters) {
    this.filters = filters;
    return this;
  }

  public UpdateMeterDto putFiltersItem(String key, Object filtersItem) {
    if (this.filters == null) {
      this.filters = new HashMap<>();
    }
    this.filters.put(key, filtersItem);
    return this;
  }

  /**
   * Optional filter definition for advanced matching.
   * @return filters
   */
  @javax.annotation.Nullable
  public Map<String, Object> getFilters() {
    return filters;
  }

  public void setFilters(@javax.annotation.Nullable Map<String, Object> filters) {
    this.filters = filters;
  }


  public UpdateMeterDto enableFiltering(@javax.annotation.Nullable Boolean enableFiltering) {
    this.enableFiltering = enableFiltering;
    return this;
  }

  /**
   * Enable filtering on usage event ingestion.
   * @return enableFiltering
   */
  @javax.annotation.Nullable
  public Boolean getEnableFiltering() {
    return enableFiltering;
  }

  public void setEnableFiltering(@javax.annotation.Nullable Boolean enableFiltering) {
    this.enableFiltering = enableFiltering;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UpdateMeterDto updateMeterDto = (UpdateMeterDto) o;
    return Objects.equals(this.name, updateMeterDto.name) &&
        Objects.equals(this.description, updateMeterDto.description) &&
        Objects.equals(this.eventName, updateMeterDto.eventName) &&
        Objects.equals(this.aggregationType, updateMeterDto.aggregationType) &&
        Objects.equals(this.aggregationKey, updateMeterDto.aggregationKey) &&
        Objects.equals(this.unit, updateMeterDto.unit) &&
        Objects.equals(this.filters, updateMeterDto.filters) &&
        Objects.equals(this.enableFiltering, updateMeterDto.enableFiltering);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, description, eventName, aggregationType, aggregationKey, unit, filters, enableFiltering);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UpdateMeterDto {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    eventName: ").append(toIndentedString(eventName)).append("\n");
    sb.append("    aggregationType: ").append(toIndentedString(aggregationType)).append("\n");
    sb.append("    aggregationKey: ").append(toIndentedString(aggregationKey)).append("\n");
    sb.append("    unit: ").append(toIndentedString(unit)).append("\n");
    sb.append("    filters: ").append(toIndentedString(filters)).append("\n");
    sb.append("    enableFiltering: ").append(toIndentedString(enableFiltering)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("name");
    openapiFields.add("description");
    openapiFields.add("eventName");
    openapiFields.add("aggregationType");
    openapiFields.add("aggregationKey");
    openapiFields.add("unit");
    openapiFields.add("filters");
    openapiFields.add("enableFiltering");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to UpdateMeterDto
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!UpdateMeterDto.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in UpdateMeterDto is not found in the empty JSON string", UpdateMeterDto.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!UpdateMeterDto.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `UpdateMeterDto` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("name") != null && !jsonObj.get("name").isJsonNull()) && !jsonObj.get("name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("name").toString()));
      }
      if ((jsonObj.get("description") != null && !jsonObj.get("description").isJsonNull()) && !jsonObj.get("description").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `description` to be a primitive type in the JSON string but got `%s`", jsonObj.get("description").toString()));
      }
      if ((jsonObj.get("eventName") != null && !jsonObj.get("eventName").isJsonNull()) && !jsonObj.get("eventName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `eventName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("eventName").toString()));
      }
      if ((jsonObj.get("aggregationType") != null && !jsonObj.get("aggregationType").isJsonNull()) && !jsonObj.get("aggregationType").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `aggregationType` to be a primitive type in the JSON string but got `%s`", jsonObj.get("aggregationType").toString()));
      }
      // validate the optional field `aggregationType`
      if (jsonObj.get("aggregationType") != null && !jsonObj.get("aggregationType").isJsonNull()) {
        AggregationTypeEnum.validateJsonElement(jsonObj.get("aggregationType"));
      }
      if ((jsonObj.get("aggregationKey") != null && !jsonObj.get("aggregationKey").isJsonNull()) && !jsonObj.get("aggregationKey").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `aggregationKey` to be a primitive type in the JSON string but got `%s`", jsonObj.get("aggregationKey").toString()));
      }
      if ((jsonObj.get("unit") != null && !jsonObj.get("unit").isJsonNull()) && !jsonObj.get("unit").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `unit` to be a primitive type in the JSON string but got `%s`", jsonObj.get("unit").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!UpdateMeterDto.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'UpdateMeterDto' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<UpdateMeterDto> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(UpdateMeterDto.class));

       return (TypeAdapter<T>) new TypeAdapter<UpdateMeterDto>() {
           @Override
           public void write(JsonWriter out, UpdateMeterDto value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public UpdateMeterDto read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of UpdateMeterDto given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of UpdateMeterDto
   * @throws IOException if the JSON string is invalid with respect to UpdateMeterDto
   */
  public static UpdateMeterDto fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, UpdateMeterDto.class);
  }

  /**
   * Convert an instance of UpdateMeterDto to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

