/*
 * Solifyn API
 * Welcome to the Solifyn API Reference. Leverage our secure endpoints to manage products and issue, validate, and manage software license keys programmatically.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.solifyn.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.solifyn.JSON;

/**
 * Represents a cryptographically secure software license key issued to a customer upon purchase or manual issuance.
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-06-11T08:41:07.343307200+07:00[Asia/Saigon]", comments = "Generator version: 7.10.0")
public class WebhookLicensePayload {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  @javax.annotation.Nonnull
  private String id;

  public static final String SERIALIZED_NAME_KEY = "key";
  @SerializedName(SERIALIZED_NAME_KEY)
  @javax.annotation.Nonnull
  private String key;

  /**
   * Lifecycle status of the license. ACTIVE &#x3D; active. DISABLED &#x3D; suspended. REVOKED &#x3D; hard-revoked.
   */
  @JsonAdapter(StatusEnum.Adapter.class)
  public enum StatusEnum {
    ACTIVE("ACTIVE"),
    
    DISABLED("DISABLED"),
    
    REVOKED("REVOKED");

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static StatusEnum fromValue(String value) {
      for (StatusEnum b : StatusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<StatusEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final StatusEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public StatusEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return StatusEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      StatusEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_STATUS = "status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  @javax.annotation.Nonnull
  private StatusEnum status;

  public static final String SERIALIZED_NAME_BUSINESS_ID = "businessId";
  @SerializedName(SERIALIZED_NAME_BUSINESS_ID)
  @javax.annotation.Nonnull
  private String businessId;

  public static final String SERIALIZED_NAME_PRODUCT_ID = "productId";
  @SerializedName(SERIALIZED_NAME_PRODUCT_ID)
  @javax.annotation.Nonnull
  private String productId;

  public static final String SERIALIZED_NAME_PAYMENT_ID = "paymentId";
  @SerializedName(SERIALIZED_NAME_PAYMENT_ID)
  @javax.annotation.Nonnull
  private String paymentId;

  public static final String SERIALIZED_NAME_CUSTOMER_ID = "customerId";
  @SerializedName(SERIALIZED_NAME_CUSTOMER_ID)
  @javax.annotation.Nonnull
  private String customerId;

  public static final String SERIALIZED_NAME_ACTIVATION_LIMIT = "activationLimit";
  @SerializedName(SERIALIZED_NAME_ACTIVATION_LIMIT)
  @javax.annotation.Nonnull
  private BigDecimal activationLimit;

  public static final String SERIALIZED_NAME_ACTIVATION_MESSAGE = "activationMessage";
  @SerializedName(SERIALIZED_NAME_ACTIVATION_MESSAGE)
  @javax.annotation.Nonnull
  private String activationMessage;

  public static final String SERIALIZED_NAME_INSTANCES_COUNT = "instancesCount";
  @SerializedName(SERIALIZED_NAME_INSTANCES_COUNT)
  @javax.annotation.Nonnull
  private BigDecimal instancesCount;

  public static final String SERIALIZED_NAME_EXPIRY_HOURS = "expiryHours";
  @SerializedName(SERIALIZED_NAME_EXPIRY_HOURS)
  @javax.annotation.Nonnull
  private BigDecimal expiryHours;

  public static final String SERIALIZED_NAME_EXPIRES_AT = "expiresAt";
  @SerializedName(SERIALIZED_NAME_EXPIRES_AT)
  @javax.annotation.Nonnull
  private String expiresAt;

  public static final String SERIALIZED_NAME_FILTERS = "filters";
  @SerializedName(SERIALIZED_NAME_FILTERS)
  @javax.annotation.Nonnull
  private Object filters;

  public static final String SERIALIZED_NAME_ARCHIVED = "archived";
  @SerializedName(SERIALIZED_NAME_ARCHIVED)
  @javax.annotation.Nonnull
  private Boolean archived;

  public static final String SERIALIZED_NAME_CREATED_AT = "createdAt";
  @SerializedName(SERIALIZED_NAME_CREATED_AT)
  @javax.annotation.Nonnull
  private String createdAt;

  public static final String SERIALIZED_NAME_UPDATED_AT = "updatedAt";
  @SerializedName(SERIALIZED_NAME_UPDATED_AT)
  @javax.annotation.Nonnull
  private String updatedAt;

  public WebhookLicensePayload() {
  }

  public WebhookLicensePayload id(@javax.annotation.Nonnull String id) {
    this.id = id;
    return this;
  }

  /**
   * The unique prefix-based identifier of the license key.
   * @return id
   */
  @javax.annotation.Nonnull
  public String getId() {
    return id;
  }

  public void setId(@javax.annotation.Nonnull String id) {
    this.id = id;
  }


  public WebhookLicensePayload key(@javax.annotation.Nonnull String key) {
    this.key = key;
    return this;
  }

  /**
   * The cryptographically generated license key string delivered to the customer.
   * @return key
   */
  @javax.annotation.Nonnull
  public String getKey() {
    return key;
  }

  public void setKey(@javax.annotation.Nonnull String key) {
    this.key = key;
  }


  public WebhookLicensePayload status(@javax.annotation.Nonnull StatusEnum status) {
    this.status = status;
    return this;
  }

  /**
   * Lifecycle status of the license. ACTIVE &#x3D; active. DISABLED &#x3D; suspended. REVOKED &#x3D; hard-revoked.
   * @return status
   */
  @javax.annotation.Nonnull
  public StatusEnum getStatus() {
    return status;
  }

  public void setStatus(@javax.annotation.Nonnull StatusEnum status) {
    this.status = status;
  }


  public WebhookLicensePayload businessId(@javax.annotation.Nonnull String businessId) {
    this.businessId = businessId;
    return this;
  }

  /**
   * The unique identifier associated with the business this license belongs to.
   * @return businessId
   */
  @javax.annotation.Nonnull
  public String getBusinessId() {
    return businessId;
  }

  public void setBusinessId(@javax.annotation.Nonnull String businessId) {
    this.businessId = businessId;
  }


  public WebhookLicensePayload productId(@javax.annotation.Nonnull String productId) {
    this.productId = productId;
    return this;
  }

  /**
   * The unique ID of the product this license key is associated with.
   * @return productId
   */
  @javax.annotation.Nonnull
  public String getProductId() {
    return productId;
  }

  public void setProductId(@javax.annotation.Nonnull String productId) {
    this.productId = productId;
  }


  public WebhookLicensePayload paymentId(@javax.annotation.Nonnull String paymentId) {
    this.paymentId = paymentId;
    return this;
  }

  /**
   * The unique payment identifier that triggered the issuance of this license key.
   * @return paymentId
   */
  @javax.annotation.Nonnull
  public String getPaymentId() {
    return paymentId;
  }

  public void setPaymentId(@javax.annotation.Nonnull String paymentId) {
    this.paymentId = paymentId;
  }


  public WebhookLicensePayload customerId(@javax.annotation.Nonnull String customerId) {
    this.customerId = customerId;
    return this;
  }

  /**
   * The unique customer identifier (ID) who received this license key.
   * @return customerId
   */
  @javax.annotation.Nonnull
  public String getCustomerId() {
    return customerId;
  }

  public void setCustomerId(@javax.annotation.Nonnull String customerId) {
    this.customerId = customerId;
  }


  public WebhookLicensePayload activationLimit(@javax.annotation.Nonnull BigDecimal activationLimit) {
    this.activationLimit = activationLimit;
    return this;
  }

  /**
   * Maximum number of simultaneous active device instances allowed for this license. Null means unlimited.
   * @return activationLimit
   */
  @javax.annotation.Nonnull
  public BigDecimal getActivationLimit() {
    return activationLimit;
  }

  public void setActivationLimit(@javax.annotation.Nonnull BigDecimal activationLimit) {
    this.activationLimit = activationLimit;
  }


  public WebhookLicensePayload activationMessage(@javax.annotation.Nonnull String activationMessage) {
    this.activationMessage = activationMessage;
    return this;
  }

  /**
   * Optional message displayed to the customer upon successful activation.
   * @return activationMessage
   */
  @javax.annotation.Nonnull
  public String getActivationMessage() {
    return activationMessage;
  }

  public void setActivationMessage(@javax.annotation.Nonnull String activationMessage) {
    this.activationMessage = activationMessage;
  }


  public WebhookLicensePayload instancesCount(@javax.annotation.Nonnull BigDecimal instancesCount) {
    this.instancesCount = instancesCount;
    return this;
  }

  /**
   * Running count of how many times this license key has been activated.
   * @return instancesCount
   */
  @javax.annotation.Nonnull
  public BigDecimal getInstancesCount() {
    return instancesCount;
  }

  public void setInstancesCount(@javax.annotation.Nonnull BigDecimal instancesCount) {
    this.instancesCount = instancesCount;
  }


  public WebhookLicensePayload expiryHours(@javax.annotation.Nonnull BigDecimal expiryHours) {
    this.expiryHours = expiryHours;
    return this;
  }

  /**
   * Relative expiry duration in hours from the time of issuance.
   * @return expiryHours
   */
  @javax.annotation.Nonnull
  public BigDecimal getExpiryHours() {
    return expiryHours;
  }

  public void setExpiryHours(@javax.annotation.Nonnull BigDecimal expiryHours) {
    this.expiryHours = expiryHours;
  }


  public WebhookLicensePayload expiresAt(@javax.annotation.Nonnull String expiresAt) {
    this.expiresAt = expiresAt;
    return this;
  }

  /**
   * Absolute expiration timestamp. The license becomes invalid after this point.
   * @return expiresAt
   */
  @javax.annotation.Nonnull
  public String getExpiresAt() {
    return expiresAt;
  }

  public void setExpiresAt(@javax.annotation.Nonnull String expiresAt) {
    this.expiresAt = expiresAt;
  }


  public WebhookLicensePayload filters(@javax.annotation.Nonnull Object filters) {
    this.filters = filters;
    return this;
  }

  /**
   * Optional custom metadata filters associated with the license.
   * @return filters
   */
  @javax.annotation.Nonnull
  public Object getFilters() {
    return filters;
  }

  public void setFilters(@javax.annotation.Nonnull Object filters) {
    this.filters = filters;
  }


  public WebhookLicensePayload archived(@javax.annotation.Nonnull Boolean archived) {
    this.archived = archived;
    return this;
  }

  /**
   * Indicates if the license key is archived.
   * @return archived
   */
  @javax.annotation.Nonnull
  public Boolean getArchived() {
    return archived;
  }

  public void setArchived(@javax.annotation.Nonnull Boolean archived) {
    this.archived = archived;
  }


  public WebhookLicensePayload createdAt(@javax.annotation.Nonnull String createdAt) {
    this.createdAt = createdAt;
    return this;
  }

  /**
   * Timestamp indicating exactly when the license key was issued.
   * @return createdAt
   */
  @javax.annotation.Nonnull
  public String getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(@javax.annotation.Nonnull String createdAt) {
    this.createdAt = createdAt;
  }


  public WebhookLicensePayload updatedAt(@javax.annotation.Nonnull String updatedAt) {
    this.updatedAt = updatedAt;
    return this;
  }

  /**
   * Timestamp indicating when the license key was last modified.
   * @return updatedAt
   */
  @javax.annotation.Nonnull
  public String getUpdatedAt() {
    return updatedAt;
  }

  public void setUpdatedAt(@javax.annotation.Nonnull String updatedAt) {
    this.updatedAt = updatedAt;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WebhookLicensePayload webhookLicensePayload = (WebhookLicensePayload) o;
    return Objects.equals(this.id, webhookLicensePayload.id) &&
        Objects.equals(this.key, webhookLicensePayload.key) &&
        Objects.equals(this.status, webhookLicensePayload.status) &&
        Objects.equals(this.businessId, webhookLicensePayload.businessId) &&
        Objects.equals(this.productId, webhookLicensePayload.productId) &&
        Objects.equals(this.paymentId, webhookLicensePayload.paymentId) &&
        Objects.equals(this.customerId, webhookLicensePayload.customerId) &&
        Objects.equals(this.activationLimit, webhookLicensePayload.activationLimit) &&
        Objects.equals(this.activationMessage, webhookLicensePayload.activationMessage) &&
        Objects.equals(this.instancesCount, webhookLicensePayload.instancesCount) &&
        Objects.equals(this.expiryHours, webhookLicensePayload.expiryHours) &&
        Objects.equals(this.expiresAt, webhookLicensePayload.expiresAt) &&
        Objects.equals(this.filters, webhookLicensePayload.filters) &&
        Objects.equals(this.archived, webhookLicensePayload.archived) &&
        Objects.equals(this.createdAt, webhookLicensePayload.createdAt) &&
        Objects.equals(this.updatedAt, webhookLicensePayload.updatedAt);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, key, status, businessId, productId, paymentId, customerId, activationLimit, activationMessage, instancesCount, expiryHours, expiresAt, filters, archived, createdAt, updatedAt);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WebhookLicensePayload {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    key: ").append(toIndentedString(key)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    businessId: ").append(toIndentedString(businessId)).append("\n");
    sb.append("    productId: ").append(toIndentedString(productId)).append("\n");
    sb.append("    paymentId: ").append(toIndentedString(paymentId)).append("\n");
    sb.append("    customerId: ").append(toIndentedString(customerId)).append("\n");
    sb.append("    activationLimit: ").append(toIndentedString(activationLimit)).append("\n");
    sb.append("    activationMessage: ").append(toIndentedString(activationMessage)).append("\n");
    sb.append("    instancesCount: ").append(toIndentedString(instancesCount)).append("\n");
    sb.append("    expiryHours: ").append(toIndentedString(expiryHours)).append("\n");
    sb.append("    expiresAt: ").append(toIndentedString(expiresAt)).append("\n");
    sb.append("    filters: ").append(toIndentedString(filters)).append("\n");
    sb.append("    archived: ").append(toIndentedString(archived)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("id");
    openapiFields.add("key");
    openapiFields.add("status");
    openapiFields.add("businessId");
    openapiFields.add("productId");
    openapiFields.add("paymentId");
    openapiFields.add("customerId");
    openapiFields.add("activationLimit");
    openapiFields.add("activationMessage");
    openapiFields.add("instancesCount");
    openapiFields.add("expiryHours");
    openapiFields.add("expiresAt");
    openapiFields.add("filters");
    openapiFields.add("archived");
    openapiFields.add("createdAt");
    openapiFields.add("updatedAt");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("id");
    openapiRequiredFields.add("key");
    openapiRequiredFields.add("status");
    openapiRequiredFields.add("businessId");
    openapiRequiredFields.add("productId");
    openapiRequiredFields.add("paymentId");
    openapiRequiredFields.add("customerId");
    openapiRequiredFields.add("activationLimit");
    openapiRequiredFields.add("activationMessage");
    openapiRequiredFields.add("instancesCount");
    openapiRequiredFields.add("expiryHours");
    openapiRequiredFields.add("expiresAt");
    openapiRequiredFields.add("filters");
    openapiRequiredFields.add("archived");
    openapiRequiredFields.add("createdAt");
    openapiRequiredFields.add("updatedAt");
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to WebhookLicensePayload
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!WebhookLicensePayload.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in WebhookLicensePayload is not found in the empty JSON string", WebhookLicensePayload.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!WebhookLicensePayload.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `WebhookLicensePayload` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : WebhookLicensePayload.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("id").toString()));
      }
      if (!jsonObj.get("key").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `key` to be a primitive type in the JSON string but got `%s`", jsonObj.get("key").toString()));
      }
      if (!jsonObj.get("status").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `status` to be a primitive type in the JSON string but got `%s`", jsonObj.get("status").toString()));
      }
      // validate the required field `status`
      StatusEnum.validateJsonElement(jsonObj.get("status"));
      if (!jsonObj.get("businessId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `businessId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("businessId").toString()));
      }
      if (!jsonObj.get("productId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `productId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("productId").toString()));
      }
      if (!jsonObj.get("paymentId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `paymentId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("paymentId").toString()));
      }
      if (!jsonObj.get("customerId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `customerId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("customerId").toString()));
      }
      if (!jsonObj.get("activationMessage").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `activationMessage` to be a primitive type in the JSON string but got `%s`", jsonObj.get("activationMessage").toString()));
      }
      if (!jsonObj.get("expiresAt").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `expiresAt` to be a primitive type in the JSON string but got `%s`", jsonObj.get("expiresAt").toString()));
      }
      if (!jsonObj.get("createdAt").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `createdAt` to be a primitive type in the JSON string but got `%s`", jsonObj.get("createdAt").toString()));
      }
      if (!jsonObj.get("updatedAt").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `updatedAt` to be a primitive type in the JSON string but got `%s`", jsonObj.get("updatedAt").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!WebhookLicensePayload.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'WebhookLicensePayload' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<WebhookLicensePayload> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(WebhookLicensePayload.class));

       return (TypeAdapter<T>) new TypeAdapter<WebhookLicensePayload>() {
           @Override
           public void write(JsonWriter out, WebhookLicensePayload value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public WebhookLicensePayload read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of WebhookLicensePayload given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of WebhookLicensePayload
   * @throws IOException if the JSON string is invalid with respect to WebhookLicensePayload
   */
  public static WebhookLicensePayload fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, WebhookLicensePayload.class);
  }

  /**
   * Convert an instance of WebhookLicensePayload to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

