/*
 * Solifyn API
 * Welcome to the Solifyn API Reference. Leverage our secure endpoints to manage products and issue, validate, and manage software license keys programmatically.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.solifyn.api;

import com.solifyn.ApiException;
import com.solifyn.model.CheckoutResponseDto;
import com.solifyn.model.CheckoutSessionDetailsDto;
import com.solifyn.model.CreateCheckoutDto;
import com.solifyn.model.CreateCollectionCheckoutDto;
import com.solifyn.model.PricePreviewResponseDto;
import com.solifyn.model.SupportedCurrenciesResponseDto;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for CheckoutApi
 */
@Disabled
public class CheckoutApiTest {

    private final CheckoutApi api = new CheckoutApi();

    /**
     * Create Checkout Session
     *
     * Create a new payment configuration for a product. Returns redirect URLs pointing to the custom checkout layout.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void checkoutCreateTest() throws ApiException {
        CreateCheckoutDto createCheckoutDto = null;
        CheckoutResponseDto response = api.checkoutCreate(createCheckoutDto);
        // TODO: test validations
    }

    /**
     * Create Collection Checkout Session
     *
     * Create a new payment configuration for a product bundle/collection.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void checkoutCreateCollectionTest() throws ApiException {
        CreateCollectionCheckoutDto createCollectionCheckoutDto = null;
        CheckoutResponseDto response = api.checkoutCreateCollection(createCollectionCheckoutDto);
        // TODO: test validations
    }

    /**
     * Get Checkout Session Details
     *
     * Retrieve checkout details to mount the custom embedded checkout.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void checkoutGetSessionTest() throws ApiException {
        String id = null;
        CheckoutSessionDetailsDto response = api.checkoutGetSession(id);
        // TODO: test validations
    }

    /**
     * Get Converted Price Preview
     *
     * Pre-calculate target currencies, applied discounts, and PWYW values before mounting the checkout.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void checkoutPricePreviewTest() throws ApiException {
        String productId = null;
        String addons = null;
        String currency = null;
        String discount = null;
        String qty = null;
        String customPrice = null;
        PricePreviewResponseDto response = api.checkoutPricePreview(productId, addons, currency, discount, qty, customPrice);
        // TODO: test validations
    }

    /**
     * Get Supported Currencies
     *
     * Retrieve all currencies supported for payouts and conversions.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void checkoutSupportedCurrenciesTest() throws ApiException {
        List<SupportedCurrenciesResponseDto> response = api.checkoutSupportedCurrencies();
        // TODO: test validations
    }

}
