/*
 * Solifyn API
 * Welcome to the Solifyn API Reference. Leverage our secure endpoints to manage products and issue, validate, and manage software license keys programmatically.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.solifyn.api;

import com.solifyn.ApiException;
import com.solifyn.model.ApiKeyResponseDto;
import com.solifyn.model.AppPortalUrlResponseDto;
import com.solifyn.model.CreateApiKeyDto;
import com.solifyn.model.CreateWebhookEndpointDto;
import com.solifyn.model.UpdateWebhookEndpointDto;
import com.solifyn.model.WebhookDeliveryResponseDto;
import com.solifyn.model.WebhookEndpointResponseDto;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for DeveloperApi
 */
@Disabled
public class DeveloperApiTest {

    private final DeveloperApi api = new DeveloperApi();

    /**
     * Create Developer API Key
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void developerCreateApiKeyTest() throws ApiException {
        CreateApiKeyDto createApiKeyDto = null;
        ApiKeyResponseDto response = api.developerCreateApiKey(createApiKeyDto);
        // TODO: test validations
    }

    /**
     * Create Webhook Endpoint
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void developerCreateWebhookTest() throws ApiException {
        CreateWebhookEndpointDto createWebhookEndpointDto = null;
        WebhookEndpointResponseDto response = api.developerCreateWebhook(createWebhookEndpointDto);
        // TODO: test validations
    }

    /**
     * Delete Webhook Endpoint
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void developerDeleteWebhookTest() throws ApiException {
        String id = null;
        api.developerDeleteWebhook(id);
        // TODO: test validations
    }

    /**
     * Retrieve Hosted Webhooks Portal URL
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void developerGetAppPortalTest() throws ApiException {
        AppPortalUrlResponseDto response = api.developerGetAppPortal();
        // TODO: test validations
    }

    /**
     * Retrieve Webhook Endpoint Details
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void developerGetWebhookTest() throws ApiException {
        String id = null;
        WebhookEndpointResponseDto response = api.developerGetWebhook(id);
        // TODO: test validations
    }

    /**
     * List Developer API Keys
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void developerListApiKeysTest() throws ApiException {
        List<ApiKeyResponseDto> response = api.developerListApiKeys();
        // TODO: test validations
    }

    /**
     * Retrieve Webhook Delivery Logs
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void developerListWebhookDeliveriesTest() throws ApiException {
        String id = null;
        List<WebhookDeliveryResponseDto> response = api.developerListWebhookDeliveries(id);
        // TODO: test validations
    }

    /**
     * List Webhook Endpoints
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void developerListWebhooksTest() throws ApiException {
        List<WebhookEndpointResponseDto> response = api.developerListWebhooks();
        // TODO: test validations
    }

    /**
     * Revoke API Key
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void developerRevokeApiKeyTest() throws ApiException {
        String id = null;
        api.developerRevokeApiKey(id);
        // TODO: test validations
    }

    /**
     * Update Webhook Endpoint
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void developerUpdateWebhookTest() throws ApiException {
        String id = null;
        UpdateWebhookEndpointDto updateWebhookEndpointDto = null;
        WebhookEndpointResponseDto response = api.developerUpdateWebhook(id, updateWebhookEndpointDto);
        // TODO: test validations
    }

}
