/*
 * Solifyn API
 * Welcome to the Solifyn API Reference. Leverage our secure endpoints to manage products and issue, validate, and manage software license keys programmatically.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.solifyn.api;

import com.solifyn.ApiException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for DigitalFileApi
 */
@Disabled
public class DigitalFileApiTest {

    private final DigitalFileApi api = new DigitalFileApi();

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void digitalFileControllerCreateTest() throws ApiException {
        api.digitalFileControllerCreate();
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void digitalFileControllerFindAllTest() throws ApiException {
        api.digitalFileControllerFindAll();
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void digitalFileControllerRemoveTest() throws ApiException {
        String id = null;
        api.digitalFileControllerRemove(id);
        // TODO: test validations
    }

}
