/*
 * Solifyn API
 * Welcome to the Solifyn API Reference. Leverage our secure endpoints to manage products and issue, validate, and manage software license keys programmatically.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.solifyn.api;

import com.solifyn.ApiException;
import java.math.BigDecimal;
import com.solifyn.model.Discount;
import com.solifyn.model.DiscountCreate;
import com.solifyn.model.DiscountUpdate;
import com.solifyn.model.DiscountsList200Response;
import com.solifyn.model.LicensesDeactivate200Response;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for DiscountsApi
 */
@Disabled
public class DiscountsApiTest {

    private final DiscountsApi api = new DiscountsApi();

    /**
     * Create Discount
     *
     * Create a new discount code within your active business.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void discountsCreateTest() throws ApiException {
        DiscountCreate discountCreate = null;
        Discount response = api.discountsCreate(discountCreate);
        // TODO: test validations
    }

    /**
     * Delete Discount
     *
     * Delete a specific discount code by ID.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void discountsDeleteTest() throws ApiException {
        String id = null;
        LicensesDeactivate200Response response = api.discountsDelete(id);
        // TODO: test validations
    }

    /**
     * Retrieve Discount
     *
     * Retrieve details of a specific discount code using its ID.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void discountsGetTest() throws ApiException {
        String id = null;
        Discount response = api.discountsGet(id);
        // TODO: test validations
    }

    /**
     * List Discounts
     *
     * List and query discounts belonging to your active business with support for fuzzy search by code, pagination, and sorting.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void discountsListTest() throws ApiException {
        String sorting = null;
        BigDecimal limit = null;
        BigDecimal page = null;
        String query = null;
        String id = null;
        DiscountsList200Response response = api.discountsList(sorting, limit, page, query, id);
        // TODO: test validations
    }

    /**
     * Update Discount
     *
     * Update details of an existing discount code.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void discountsUpdateTest() throws ApiException {
        String id = null;
        DiscountUpdate discountUpdate = null;
        Discount response = api.discountsUpdate(id, discountUpdate);
        // TODO: test validations
    }

    /**
     * Validate Code
     *
     * Validate if a specific discount code is active and valid for purchase checkout.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void discountsValidateTest() throws ApiException {
        String code = null;
        String businessId = null;
        Discount response = api.discountsValidate(code, businessId);
        // TODO: test validations
    }

}
