/*
 * Solifyn API
 * Welcome to the Solifyn API Reference. Leverage our secure endpoints to manage products and issue, validate, and manage software license keys programmatically.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.solifyn.api;

import com.solifyn.ApiException;
import com.solifyn.model.GithubReposResponseDto;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for GitHubIntegrationApi
 */
@Disabled
public class GitHubIntegrationApiTest {

    private final GitHubIntegrationApi api = new GitHubIntegrationApi();

    /**
     * Get GitHub App Installation URL
     *
     * Generates the URL to install the system-wide GitHub App onto the merchant&#39;s GitHub account/org.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void githubGetInstallUrlTest() throws ApiException {
        String productId = null;
        api.githubGetInstallUrl(productId);
        // TODO: test validations
    }

    /**
     * List Available GitHub Repositories
     *
     * Retrieves all repositories accessible by the merchant&#39;s installed GitHub App.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void githubListReposTest() throws ApiException {
        List<GithubReposResponseDto> response = api.githubListRepos();
        // TODO: test validations
    }

}
