/*
 * Solifyn API
 * Welcome to the Solifyn API Reference. Leverage our secure endpoints to manage products and issue, validate, and manage software license keys programmatically.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.solifyn.api;

import com.solifyn.ApiException;
import com.solifyn.model.Instance;
import com.solifyn.model.License;
import com.solifyn.model.LicensesCreateRequest;
import com.solifyn.model.LicensesUpdateInstancePostRequest;
import com.solifyn.model.LicensesUpdateRequest;
import java.util.UUID;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for LicenseKeysApi
 */
@Disabled
public class LicenseKeysApiTest {

    private final LicenseKeysApi api = new LicenseKeysApi();

    /**
     * Create License Key
     *
     * Manually issue a new license key for a specific product.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void licensesCreateTest() throws ApiException {
        LicensesCreateRequest licensesCreateRequest = null;
        License response = api.licensesCreate(licensesCreateRequest);
        // TODO: test validations
    }

    /**
     * Force Delete Instance
     *
     * Administrative endpoint to force-delete an instance globally by its database ID.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void licensesDeleteInstanceTest() throws ApiException {
        String instanceId = null;
        Instance response = api.licensesDeleteInstance(instanceId);
        // TODO: test validations
    }

    /**
     * Get License Key
     *
     * Retrieve complete administrative details of a specific license key.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void licensesGetTest() throws ApiException {
        UUID id = null;
        License response = api.licensesGet(id);
        // TODO: test validations
    }

    /**
     * Get License Key Instance
     *
     * Retrieve administrative details of a specific software license instance.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void licensesGetInstanceTest() throws ApiException {
        UUID id = null;
        String instanceId = null;
        Instance response = api.licensesGetInstance(id, instanceId);
        // TODO: test validations
    }

    /**
     * Get License Key Instances
     *
     * Retrieve all active devices/instances for a specific administrative license key.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void licensesGetInstancesTest() throws ApiException {
        String id = null;
        List<Instance> response = api.licensesGetInstances(id);
        // TODO: test validations
    }

    /**
     * List License Keys
     *
     * List all administrative license keys belonging to products under your active business.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void licensesListTest() throws ApiException {
        List<License> response = api.licensesList();
        // TODO: test validations
    }

    /**
     * Toggle License Status
     *
     * Toggle the status of a specific license key between ACTIVE and DISABLED.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void licensesToggleTest() throws ApiException {
        String id = null;
        License response = api.licensesToggle(id);
        // TODO: test validations
    }

    /**
     * Update License Key
     *
     * Update limits or status of an existing license key.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void licensesUpdateTest() throws ApiException {
        UUID id = null;
        LicensesUpdateRequest licensesUpdateRequest = null;
        License response = api.licensesUpdate(id, licensesUpdateRequest);
        // TODO: test validations
    }

    /**
     * Update License Key Instance
     *
     * Update administrative details (like friendly display name or custom IP) of an active license device instance.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void licensesUpdateInstanceTest() throws ApiException {
        String instanceId = null;
        UUID id = null;
        LicensesUpdateInstancePostRequest licensesUpdateInstancePostRequest = null;
        Instance response = api.licensesUpdateInstance(instanceId, id, licensesUpdateInstancePostRequest);
        // TODO: test validations
    }

    /**
     * Update License Key Instance (POST)
     *
     * Alternative POST endpoint to update administrative details (like friendly display name or custom IP) of an active license device instance.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void licensesUpdateInstancePostTest() throws ApiException {
        String instanceId = null;
        UUID id = null;
        LicensesUpdateInstancePostRequest licensesUpdateInstancePostRequest = null;
        Instance response = api.licensesUpdateInstancePost(instanceId, id, licensesUpdateInstancePostRequest);
        // TODO: test validations
    }

}
