/*
 * Solifyn API
 * Welcome to the Solifyn API Reference. Leverage our secure endpoints to manage products and issue, validate, and manage software license keys programmatically.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.solifyn.api;

import com.solifyn.ApiException;
import java.math.BigDecimal;
import com.solifyn.model.PayoutAccessToken;
import com.solifyn.model.PayoutAccount;
import com.solifyn.model.PayoutAccountLink;
import com.solifyn.model.PayoutMethodList;
import com.solifyn.model.PayoutVerificationList;
import com.solifyn.model.Withdrawal;
import com.solifyn.model.WithdrawalCreate;
import com.solifyn.model.WithdrawalList;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for PayoutsApi
 */
@Disabled
public class PayoutsApiTest {

    private final PayoutsApi api = new PayoutsApi();

    /**
     * Create Withdrawal
     *
     * Initiate a balance withdrawal transfer request.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void payoutsCreateWithdrawalTest() throws ApiException {
        WithdrawalCreate withdrawalCreate = null;
        Withdrawal response = api.payoutsCreateWithdrawal(withdrawalCreate);
        // TODO: test validations
    }

    /**
     * Retrieve Payout Account
     *
     * Retrieve general status and information of onboarding payout accounts.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void payoutsGetAccountTest() throws ApiException {
        PayoutAccount response = api.payoutsGetAccount();
        // TODO: test validations
    }

    /**
     * Create Account Link
     *
     * Generate temporary links for onboarding or viewing portals.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void payoutsGetAccountLinkTest() throws ApiException {
        String useCase = null;
        PayoutAccountLink response = api.payoutsGetAccountLink(useCase);
        // TODO: test validations
    }

    /**
     * Generate Portal Access Token
     *
     * Generate temporary credentials to access the embed portal.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void payoutsGetTokenTest() throws ApiException {
        PayoutAccessToken response = api.payoutsGetToken();
        // TODO: test validations
    }

    /**
     * Get Withdrawals List
     *
     * Retrieve withdrawal records for the active business.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void payoutsGetWithdrawalsTest() throws ApiException {
        BigDecimal limit = null;
        BigDecimal page = null;
        WithdrawalList response = api.payoutsGetWithdrawals(limit, page);
        // TODO: test validations
    }

    /**
     * List Payout Methods
     *
     * List saved payout destinations (bank accounts, cards).
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void payoutsListMethodsTest() throws ApiException {
        BigDecimal limit = null;
        BigDecimal page = null;
        PayoutMethodList response = api.payoutsListMethods(limit, page);
        // TODO: test validations
    }

    /**
     * List Verifications
     *
     * Retrieve pending or completed KYC verification checks.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void payoutsListVerificationsTest() throws ApiException {
        BigDecimal limit = null;
        BigDecimal page = null;
        PayoutVerificationList response = api.payoutsListVerifications(limit, page);
        // TODO: test validations
    }

    /**
     * List Withdrawals
     *
     * Retrieve a list of past withdrawal history.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void payoutsListWithdrawalsTest() throws ApiException {
        BigDecimal limit = null;
        BigDecimal page = null;
        WithdrawalList response = api.payoutsListWithdrawals(limit, page);
        // TODO: test validations
    }

}
