/*
 * Solifyn API
 * Welcome to the Solifyn API Reference. Leverage our secure endpoints to manage products and issue, validate, and manage software license keys programmatically.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.solifyn.api;

import com.solifyn.ApiException;
import com.solifyn.model.UserPage;
import com.solifyn.model.UserSettings;
import com.solifyn.model.UserStats;
import com.solifyn.model.UserTheme;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for UserProfileThemesApi
 */
@Disabled
public class UserProfileThemesApiTest {

    private final UserProfileThemesApi api = new UserProfileThemesApi();

    /**
     * Get My Page details
     *
     * Retrieve page settings and custom content configured for the store.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void usersGetMyPageTest() throws ApiException {
        UserPage response = api.usersGetMyPage();
        // TODO: test validations
    }

    /**
     * Get My Theme
     *
     * Retrieve theme configurations for the active business context.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void usersGetMyThemeTest() throws ApiException {
        UserTheme response = api.usersGetMyTheme();
        // TODO: test validations
    }

    /**
     * Retrieve User Settings
     *
     * Retrieve profile settings and notification preferences for the user.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void usersGetSettingsTest() throws ApiException {
        UserSettings response = api.usersGetSettings();
        // TODO: test validations
    }

    /**
     * Get Dashboard Statistics
     *
     * Retrieve general analytics stats (revenue, order counts, etc.) for dashboard graphs.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void usersGetStatsTest() throws ApiException {
        UserStats response = api.usersGetStats();
        // TODO: test validations
    }

    /**
     * Get Theme by Subdomain
     *
     * Retrieve public theme configuration details by store subdomain.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void usersGetThemeBySubdomainTest() throws ApiException {
        String subdomain = null;
        UserTheme response = api.usersGetThemeBySubdomain(subdomain);
        // TODO: test validations
    }

}
