/*
 * Solifyn API
 * Welcome to the Solifyn API Reference. Leverage our secure endpoints to manage products and issue, validate, and manage software license keys programmatically.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.solifyn.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.time.OffsetDateTime;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for Business
 */
public class BusinessTest {
    private final Business model = new Business();

    /**
     * Model tests for Business
     */
    @Test
    public void testBusiness() {
        // TODO: test Business
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'title'
     */
    @Test
    public void titleTest() {
        // TODO: test title
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'whopId'
     */
    @Test
    public void whopIdTest() {
        // TODO: test whopId
    }

    /**
     * Test the property 'merchantId'
     */
    @Test
    public void merchantIdTest() {
        // TODO: test merchantId
    }

    /**
     * Test the property 'verified'
     */
    @Test
    public void verifiedTest() {
        // TODO: test verified
    }

    /**
     * Test the property 'sendCustomerEmails'
     */
    @Test
    public void sendCustomerEmailsTest() {
        // TODO: test sendCustomerEmails
    }

    /**
     * Test the property 'memberCount'
     */
    @Test
    public void memberCountTest() {
        // TODO: test memberCount
    }

    /**
     * Test the property 'route'
     */
    @Test
    public void routeTest() {
        // TODO: test route
    }

    /**
     * Test the property 'defaultCurrency'
     */
    @Test
    public void defaultCurrencyTest() {
        // TODO: test defaultCurrency
    }

    /**
     * Test the property 'publishedReviewsCount'
     */
    @Test
    public void publishedReviewsCountTest() {
        // TODO: test publishedReviewsCount
    }

    /**
     * Test the property 'metadata'
     */
    @Test
    public void metadataTest() {
        // TODO: test metadata
    }

    /**
     * Test the property 'targetAudience'
     */
    @Test
    public void targetAudienceTest() {
        // TODO: test targetAudience
    }

    /**
     * Test the property 'socialLinks'
     */
    @Test
    public void socialLinksTest() {
        // TODO: test socialLinks
    }

    /**
     * Test the property 'affiliateInstructions'
     */
    @Test
    public void affiliateInstructionsTest() {
        // TODO: test affiliateInstructions
    }

    /**
     * Test the property 'whopCreatedAt'
     */
    @Test
    public void whopCreatedAtTest() {
        // TODO: test whopCreatedAt
    }

    /**
     * Test the property 'whopUpdatedAt'
     */
    @Test
    public void whopUpdatedAtTest() {
        // TODO: test whopUpdatedAt
    }

    /**
     * Test the property 'createdAt'
     */
    @Test
    public void createdAtTest() {
        // TODO: test createdAt
    }

    /**
     * Test the property 'updatedAt'
     */
    @Test
    public void updatedAtTest() {
        // TODO: test updatedAt
    }

    /**
     * Test the property 'logoUrl'
     */
    @Test
    public void logoUrlTest() {
        // TODO: test logoUrl
    }

}
