/*
 * Solifyn API
 * Welcome to the Solifyn API Reference. Leverage our secure endpoints to manage products and issue, validate, and manage software license keys programmatically.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.solifyn.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.solifyn.model.RevokeSeatDto;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for OrderRefundCreate
 */
public class OrderRefundCreateTest {
    private final OrderRefundCreate model = new OrderRefundCreate();

    /**
     * Model tests for OrderRefundCreate
     */
    @Test
    public void testOrderRefundCreate() {
        // TODO: test OrderRefundCreate
    }

    /**
     * Test the property 'amount'
     */
    @Test
    public void amountTest() {
        // TODO: test amount
    }

    /**
     * Test the property 'isFullRefund'
     */
    @Test
    public void isFullRefundTest() {
        // TODO: test isFullRefund
    }

    /**
     * Test the property 'idempotencyKey'
     */
    @Test
    public void idempotencyKeyTest() {
        // TODO: test idempotencyKey
    }

    /**
     * Test the property 'autoRevokeSeats'
     */
    @Test
    public void autoRevokeSeatsTest() {
        // TODO: test autoRevokeSeats
    }

    /**
     * Test the property 'revokeSeats'
     */
    @Test
    public void revokeSeatsTest() {
        // TODO: test revokeSeats
    }

}
