/*
 * Solifyn API
 * Welcome to the Solifyn API Reference. Leverage our secure endpoints to manage products and issue, validate, and manage software license keys programmatically.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.solifyn.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.solifyn.model.ProductCreateAddonsInner;
import com.solifyn.model.ProductCreateCustomFieldsInner;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ProductCreate
 */
public class ProductCreateTest {
    private final ProductCreate model = new ProductCreate();

    /**
     * Model tests for ProductCreate
     */
    @Test
    public void testProductCreate() {
        // TODO: test ProductCreate
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'price'
     */
    @Test
    public void priceTest() {
        // TODO: test price
    }

    /**
     * Test the property 'currency'
     */
    @Test
    public void currencyTest() {
        // TODO: test currency
    }

    /**
     * Test the property 'imageUrl'
     */
    @Test
    public void imageUrlTest() {
        // TODO: test imageUrl
    }

    /**
     * Test the property 'taxCategory'
     */
    @Test
    public void taxCategoryTest() {
        // TODO: test taxCategory
    }

    /**
     * Test the property 'discount'
     */
    @Test
    public void discountTest() {
        // TODO: test discount
    }

    /**
     * Test the property 'hasLicenseKey'
     */
    @Test
    public void hasLicenseKeyTest() {
        // TODO: test hasLicenseKey
    }

    /**
     * Test the property 'hasDigitalDelivery'
     */
    @Test
    public void hasDigitalDeliveryTest() {
        // TODO: test hasDigitalDelivery
    }

    /**
     * Test the property 'hasGithubAccess'
     */
    @Test
    public void hasGithubAccessTest() {
        // TODO: test hasGithubAccess
    }

    /**
     * Test the property 'githubRepo'
     */
    @Test
    public void githubRepoTest() {
        // TODO: test githubRepo
    }

    /**
     * Test the property 'githubPermission'
     */
    @Test
    public void githubPermissionTest() {
        // TODO: test githubPermission
    }

    /**
     * Test the property 'isTaxInclusive'
     */
    @Test
    public void isTaxInclusiveTest() {
        // TODO: test isTaxInclusive
    }

    /**
     * Test the property 'activationLimit'
     */
    @Test
    public void activationLimitTest() {
        // TODO: test activationLimit
    }

    /**
     * Test the property 'brandId'
     */
    @Test
    public void brandIdTest() {
        // TODO: test brandId
    }

    /**
     * Test the property 'billingPeriod'
     */
    @Test
    public void billingPeriodTest() {
        // TODO: test billingPeriod
    }

    /**
     * Test the property 'trialPeriodDays'
     */
    @Test
    public void trialPeriodDaysTest() {
        // TODO: test trialPeriodDays
    }

    /**
     * Test the property 'expirationDays'
     */
    @Test
    public void expirationDaysTest() {
        // TODO: test expirationDays
    }

    /**
     * Test the property 'statementDescriptor'
     */
    @Test
    public void statementDescriptorTest() {
        // TODO: test statementDescriptor
    }

    /**
     * Test the property 'payWhatYouWant'
     */
    @Test
    public void payWhatYouWantTest() {
        // TODO: test payWhatYouWant
    }

    /**
     * Test the property 'metadata'
     */
    @Test
    public void metadataTest() {
        // TODO: test metadata
    }

    /**
     * Test the property 'customFields'
     */
    @Test
    public void customFieldsTest() {
        // TODO: test customFields
    }

    /**
     * Test the property 'stock'
     */
    @Test
    public void stockTest() {
        // TODO: test stock
    }

    /**
     * Test the property 'isListed'
     */
    @Test
    public void isListedTest() {
        // TODO: test isListed
    }

    /**
     * Test the property 'isFree'
     */
    @Test
    public void isFreeTest() {
        // TODO: test isFree
    }

    /**
     * Test the property 'addons'
     */
    @Test
    public void addonsTest() {
        // TODO: test addons
    }

}
