/*
 * Solifyn API
 * Welcome to the Solifyn API Reference. Leverage our secure endpoints to manage products and issue, validate, and manage software license keys programmatically.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.solifyn.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for SyncLoginDto
 */
public class SyncLoginDtoTest {
    private final SyncLoginDto model = new SyncLoginDto();

    /**
     * Model tests for SyncLoginDto
     */
    @Test
    public void testSyncLoginDto() {
        // TODO: test SyncLoginDto
    }

    /**
     * Test the property 'liveToken'
     */
    @Test
    public void liveTokenTest() {
        // TODO: test liveToken
    }

}
